# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add run series.

Revision ID: f934b49300f8
Revises: e78facade196
Create Date: 2026-05-26 16:04:15.523022
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "f934b49300f8"
down_revision: str | Sequence[str] | None = "e78facade196"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.add_column(sa.Column("series_id", sa.BigInteger(), nullable=True))
        batch_op.create_index("idx_run_series_id", ["series_id"], unique=False)

    op.create_table(
        "run_series",
        sa.Column("series_id", sa.BigInteger(), nullable=False),
        sa.Column("federation", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("series_id"),
    )

    op.create_table(
        "series_context",
        sa.Column("series_id", sa.BigInteger(), nullable=False),
        sa.Column("context", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("series_id"),
    )

    op.create_table(
        "series_runs",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("series_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    with op.batch_alter_table("series_runs", schema=None) as batch_op:
        batch_op.create_index("idx_series_runs_series_id", ["series_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("series_runs")

    op.drop_table("series_context")

    op.drop_table("run_series")

    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index("idx_run_series_id")
        batch_op.drop_column("series_id")
    # ### end Alembic commands ###
