# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add object push session tables.

Revision ID: cf405f09bb06
Revises: 1289dca56546
Create Date: 2026-07-10 15:39:46.076260
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "cf405f09bb06"
down_revision: str | Sequence[str] | None = "1289dca56546"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_push_sessions",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("pending_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("object_push_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_object_push_sessions_expires_at", ["expires_at"], unique=False
        )
        batch_op.create_index(
            "idx_object_push_sessions_run_id", ["run_id"], unique=False
        )

    op.create_table(
        "object_push_session_pending",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["object_push_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id", "object_id"),
    )
    with op.batch_alter_table("object_push_session_pending", schema=None) as batch_op:
        batch_op.create_index(
            "idx_object_push_session_pending_object_id_session_id",
            ["object_id", "session_id"],
            unique=False,
        )

    op.create_table(
        "object_push_session_roots",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("root_object_id", sa.String(), primary_key=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["object_push_sessions.session_id"], ondelete="CASCADE"
        ),
    )
    with op.batch_alter_table("object_push_session_roots", schema=None) as batch_op:
        batch_op.create_index(
            "idx_object_push_session_roots_session_id", ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("object_push_session_roots", schema=None) as batch_op:
        batch_op.drop_index("idx_object_push_session_roots_session_id")

    op.drop_table("object_push_session_roots")
    with op.batch_alter_table("object_push_session_pending", schema=None) as batch_op:
        batch_op.drop_index("idx_object_push_session_pending_object_id_session_id")

    op.drop_table("object_push_session_pending")
    with op.batch_alter_table("object_push_sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_object_push_sessions_run_id")
        batch_op.drop_index("idx_object_push_sessions_expires_at")

    op.drop_table("object_push_sessions")
    # ### end Alembic commands ###
