# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Remove run type from run table.

Revision ID: 79ed7925e1f4
Revises: b2f7c9e5a4d1
Create Date: 2026-06-19 16:44:59.510004
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "79ed7925e1f4"
down_revision: str | Sequence[str] | None = "b2f7c9e5a4d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

AGENT_APP_RUN_TYPE = "agentapp"
SERVER_APP_RUN_TYPE = "serverapp"
SIMULATION_RUN_TYPE = "simulation"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_column("run_type")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "run_type",
                sa.VARCHAR(),
                server_default=SERVER_APP_RUN_TYPE,
                nullable=False,
            )
        )

    op.execute(
        sa.text(
            """
            UPDATE run
            SET run_type = CASE (
                SELECT task.type
                FROM task
                WHERE task.task_id = run.primary_task_id
            )
                WHEN 'flwr-agentapp' THEN :agent_app_run_type
                WHEN 'flwr-simulation' THEN :simulation_run_type
                ELSE :server_app_run_type
            END
            """
        ).bindparams(
            agent_app_run_type=AGENT_APP_RUN_TYPE,
            simulation_run_type=SIMULATION_RUN_TYPE,
            server_app_run_type=SERVER_APP_RUN_TYPE,
        )
    )

    # ### end Alembic commands ###
