# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Store automation run request.

Revision ID: 28482626dbdc
Revises: cfda9accf4ec
Create Date: 2026-07-27 13:35:48.925302
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "28482626dbdc"
down_revision: str | Sequence[str] | None = "cfda9accf4ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("automation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("start_run_request", sa.LargeBinary(), nullable=True)
        )

    # Existing automations cannot be reconstructed as unresolved StartRun requests.
    op.execute("UPDATE automation SET status = 'failed' WHERE status = 'active'")

    with op.batch_alter_table("automation", schema=None) as batch_op:
        batch_op.drop_column("fab_hash")
        batch_op.drop_column("override_config")
        batch_op.drop_column("primary_task_type")
        batch_op.drop_column("fab_id")
        batch_op.drop_column("federation_config")
        batch_op.drop_column("fab_version")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("automation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fab_version", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("federation_config", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("fab_id", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("primary_task_type", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("override_config", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("fab_hash", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("start_run_request")

    # ### end Alembic commands ###
