# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add automations.

Revision ID: 1289dca56546
Revises: f3bd92e61ee6
Create Date: 2026-07-08 10:41:50.652339
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "1289dca56546"
down_revision: str | Sequence[str] | None = "f3bd92e61ee6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation",
        sa.Column(
            "automation_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("series_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("fab_id", sa.String(), nullable=True),
        sa.Column("fab_version", sa.String(), nullable=True),
        sa.Column("fab_hash", sa.String(), nullable=True),
        sa.Column("override_config", sa.String(), nullable=False),
        sa.Column("federation_config", sa.String(), nullable=True),
        sa.Column("primary_task_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("next_run_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("fixed_interval", sa.BigInteger(), nullable=True),
        sa.Column("remaining_runs", sa.Integer(), nullable=True),
        sa.Column("stopped_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("automation_id"),
    )
    with op.batch_alter_table("automation", schema=None) as batch_op:
        batch_op.create_index(
            "idx_automation_federation_id_status_updated_at",
            ["federation_id", "status", "updated_at"],
            unique=False,
        )
        batch_op.create_index(
            "idx_automation_status_next_run_at", ["status", "next_run_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("automation", schema=None) as batch_op:
        batch_op.drop_index("idx_automation_status_next_run_at")
        batch_op.drop_index("idx_automation_federation_id_status_updated_at")

    op.drop_table("automation")
    # ### end Alembic commands ###
