# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add federation app table.

Revision ID: 63be1836ddca
Revises: 7208a0cbdcd7
Create Date: 2026-08-14 15:50:13.685437
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from flwr.supercore.state.schema.types import UTCDateTime

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "63be1836ddca"
down_revision: str | Sequence[str] | None = "7208a0cbdcd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "federation_app",
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("app_id", sa.String(), nullable=False),
        sa.Column("fab_hash", sa.String(), nullable=False),
        sa.Column("app_type", sa.String(), nullable=False),
        sa.Column("added_by", sa.String(), nullable=False),
        sa.Column(
            "added_at",
            UTCDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("federation_id", "app_id"),
    )
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.create_index(
            "idx_federation_app_federation_id_added_at",
            ["federation_id", "added_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.drop_index("idx_federation_app_federation_id_added_at")

    op.drop_table("federation_app")
    # ### end Alembic commands ###
