# Copyright 2025 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Common Flower arguments."""


import argparse
import sys
from logging import DEBUG, ERROR, INFO, WARN
from os.path import isfile
from pathlib import Path
from typing import cast

from flwr.common.constant import RUNTIME_DEPENDENCY_INSTALL
from flwr.common.logger import log


def add_args_runtime_dependency_install(
    parser: argparse.ArgumentParser,
    default: bool = RUNTIME_DEPENDENCY_INSTALL,
    include_disable_flag: bool = False,
    allow_flag_help: str | None = None,
) -> None:
    """Add arguments controlling runtime dependency installation.

    Ensure only enable or disable flags are present. For SuperLink, also include
    the argument to disable runtime dependency installation and a deprecation
    notice for `--allow-runtime-dependency-installation`.
    """
    default_state = "enabled" if default else "disabled"
    add_argument = (
        parser.add_mutually_exclusive_group().add_argument
        if include_disable_flag
        else parser.add_argument
    )
    if include_disable_flag:
        add_argument(
            "--disable-runtime-dependency-installation",
            action="store_false",
            dest="runtime_dependency_install",
            default=default,
            help="Disable runtime installation of app dependencies via `uv sync`. "
            f"By default, runtime dependency installation is {default_state}.",
        )
    add_argument(
        "--allow-runtime-dependency-installation",
        action="store_true",
        dest="runtime_dependency_install",
        default=default,
        help=(
            allow_flag_help
            or "Allow runtime installation of app dependencies via `uv sync`."
        ),
    )


def add_args_flwr_app_common(parser: argparse.ArgumentParser) -> None:
    """Add common Flower arguments for flwr-*app to the provided parser."""
    token_group = parser.add_mutually_exclusive_group(required=True)
    token_group.add_argument(
        "--token",
        type=str,
        help="Unique token generated by the Runtime API for each app execution",
    )
    token_group.add_argument(
        "--token-file",
        type=str,
        help=(
            "Path to a file containing the unique token generated by the Runtime API "
            "for each app execution"
        ),
    )
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Run the server without HTTPS, regardless of whether certificate "
        "paths are provided. Data transmitted between the gRPC client and server "
        "is not encrypted. By default, the server runs with HTTPS enabled. "
        "Use this flag only if you understand the risks.",
    )
    parser.add_argument(
        "--root-certificates",
        metavar="ROOT_CERT",
        type=str,
        help="Path to a PEM-encoded root CA certificate (or CA bundle) used to verify "
        "the server's TLS certificate. This is not a client certificate for mTLS.",
    )
    parser.add_argument(
        "--parent-pid",
        type=int,
        default=None,
        help="The PID of the parent process. When set, the process will terminate "
        "when the parent process exits.",
    )
    add_args_runtime_dependency_install(parser)


def try_obtain_flwr_app_token(args: argparse.Namespace) -> str:
    """Validate and return the token from CLI args or a token file."""
    token = cast(str | None, getattr(args, "token", None))
    if token is not None:
        token = token.strip()
        if not token:
            sys.exit("Argument `--token` does not contain a token.")
        return token

    token_file = cast(str | None, getattr(args, "token_file", None))
    if token_file is None:
        sys.exit("Either '--token' or '--token-file' must be specified.")

    token_file_path = Path(token_file).expanduser()
    if not isfile(token_file_path):
        sys.exit("Path argument `--token-file` does not point to a file.")

    token = token_file_path.read_text(encoding="utf-8").strip()
    if not token:
        sys.exit("Path argument `--token-file` does not contain a token.")

    return token


def try_obtain_root_certificates(
    args: argparse.Namespace,
    grpc_server_address: str,
) -> bytes | str | None:
    """Validate and return the root certificates."""
    root_cert_path: str | None = args.root_certificates
    if args.insecure:
        if root_cert_path is not None:
            sys.exit(
                "Conflicting options: The '--insecure' flag disables HTTPS, "
                "but '--root-certificates' was also specified. Please remove "
                "the '--root-certificates' option when running in insecure mode, "
                "or omit '--insecure' to use HTTPS."
            )
        log(
            WARN,
            "Option `--insecure` was set. Starting insecure HTTP channel to %s.",
            grpc_server_address,
        )
        root_certificates = None
    else:
        # Load the certificates if provided, or load the system certificates
        if root_cert_path is None:
            log(INFO, "Using system certificates for TLS connection")
            root_certificates = None
        elif not isfile(root_cert_path):
            log(ERROR, "Path argument `--root-certificates` does not point to a file.")
            sys.exit(1)
        else:
            root_certificates = Path(root_cert_path).expanduser().read_bytes()
        log(
            DEBUG,
            "Starting secure HTTPS channel to %s "
            "with the following certificates: %s.",
            grpc_server_address,
            root_cert_path,
        )
    return root_certificates


def try_obtain_server_certificates(
    args: argparse.Namespace,
) -> tuple[bytes, bytes, bytes] | None:
    """Validate and return the CA cert, server cert, and server private key."""
    # Check if certificates are provided
    if args.ssl_certfile and args.ssl_keyfile and args.ssl_ca_certfile:
        if not isfile(args.ssl_ca_certfile):
            sys.exit("Path argument `--ssl-ca-certfile` does not point to a file.")
        if not isfile(args.ssl_certfile):
            sys.exit("Path argument `--ssl-certfile` does not point to a file.")
        if not isfile(args.ssl_keyfile):
            sys.exit("Path argument `--ssl-keyfile` does not point to a file.")
        certificates = (
            Path(args.ssl_ca_certfile).expanduser().read_bytes(),  # CA certificate
            Path(args.ssl_certfile).expanduser().read_bytes(),  # server certificate
            Path(args.ssl_keyfile).expanduser().read_bytes(),  # server private key
        )
        return certificates
    if args.ssl_certfile or args.ssl_keyfile or args.ssl_ca_certfile:
        sys.exit(
            "You need to provide valid file paths to `--ssl-certfile`, "
            "`--ssl-keyfile`, and `—-ssl-ca-certfile` to create a secure "
            "connection in Fleet API server (gRPC-rere)."
        )
    log(
        ERROR,
        "Certificates are required unless running in insecure mode. "
        "Please provide certificate paths to `--ssl-certfile`, "
        "`--ssl-keyfile`, and `—-ssl-ca-certfile` or run the server "
        "in insecure mode using '--insecure' if you understand the risks.",
    )
    sys.exit(1)
