"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import collections.abc
import flwr.proto.fab_pb2
import flwr.proto.federation_config_pb2
import flwr.proto.federation_pb2
import flwr.proto.message_pb2
import flwr.proto.node_pb2
import flwr.proto.run_pb2
import flwr.proto.runseries_pb2
import flwr.proto.task_pb2
import flwr.proto.transport_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StartRunRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class OverrideConfigEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> flwr.proto.transport_pb2.Scalar: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: flwr.proto.transport_pb2.Scalar | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    FAB_FIELD_NUMBER: builtins.int
    OVERRIDE_CONFIG_FIELD_NUMBER: builtins.int
    OVERRIDE_FEDERATION_CONFIG_FIELD_NUMBER: builtins.int
    APP_SPEC_FIELD_NUMBER: builtins.int
    FEDERATION_FIELD_NUMBER: builtins.int
    SERIES_ID_FIELD_NUMBER: builtins.int
    CONNECTOR_REFS_FIELD_NUMBER: builtins.int
    app_spec: builtins.str
    federation: builtins.str
    series_id: builtins.int
    @property
    def fab(self) -> flwr.proto.fab_pb2.Fab: ...
    @property
    def override_config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, flwr.proto.transport_pb2.Scalar]: ...
    @property
    def override_federation_config(self) -> flwr.proto.federation_config_pb2.SimulationConfig: ...
    @property
    def connector_refs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        fab: flwr.proto.fab_pb2.Fab | None = ...,
        override_config: collections.abc.Mapping[builtins.str, flwr.proto.transport_pb2.Scalar] | None = ...,
        override_federation_config: flwr.proto.federation_config_pb2.SimulationConfig | None = ...,
        app_spec: builtins.str = ...,
        federation: builtins.str = ...,
        series_id: builtins.int | None = ...,
        connector_refs: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_series_id", b"_series_id", "fab", b"fab", "override_federation_config", b"override_federation_config", "series_id", b"series_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_series_id", b"_series_id", "app_spec", b"app_spec", "connector_refs", b"connector_refs", "fab", b"fab", "federation", b"federation", "override_config", b"override_config", "override_federation_config", b"override_federation_config", "series_id", b"series_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_series_id", b"_series_id"]) -> typing.Literal["series_id"] | None: ...

global___StartRunRequest = StartRunRequest

@typing.final
class StartRunResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    NOTE_FIELD_NUMBER: builtins.int
    SERIES_ID_FIELD_NUMBER: builtins.int
    FEDERATION_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    note: builtins.str
    series_id: builtins.int
    federation: builtins.str
    def __init__(
        self,
        *,
        run_id: builtins.int | None = ...,
        note: builtins.str | None = ...,
        series_id: builtins.int | None = ...,
        federation: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_note", b"_note", "_run_id", b"_run_id", "_series_id", b"_series_id", "note", b"note", "run_id", b"run_id", "series_id", b"series_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_note", b"_note", "_run_id", b"_run_id", "_series_id", b"_series_id", "federation", b"federation", "note", b"note", "run_id", b"run_id", "series_id", b"series_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_note", b"_note"]) -> typing.Literal["note"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_run_id", b"_run_id"]) -> typing.Literal["run_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_series_id", b"_series_id"]) -> typing.Literal["series_id"] | None: ...

global___StartRunResponse = StartRunResponse

@typing.final
class StartAutomationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_RUN_REQUEST_FIELD_NUMBER: builtins.int
    START_AT_FIELD_NUMBER: builtins.int
    FIXED_INTERVAL_FIELD_NUMBER: builtins.int
    MAX_RUNS_FIELD_NUMBER: builtins.int
    start_at: builtins.str
    fixed_interval: builtins.int
    max_runs: builtins.int
    @property
    def start_run_request(self) -> global___StartRunRequest: ...
    def __init__(
        self,
        *,
        start_run_request: global___StartRunRequest | None = ...,
        start_at: builtins.str | None = ...,
        fixed_interval: builtins.int | None = ...,
        max_runs: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_fixed_interval", b"_fixed_interval", "_max_runs", b"_max_runs", "_start_at", b"_start_at", "fixed_interval", b"fixed_interval", "max_runs", b"max_runs", "start_at", b"start_at", "start_run_request", b"start_run_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_fixed_interval", b"_fixed_interval", "_max_runs", b"_max_runs", "_start_at", b"_start_at", "fixed_interval", b"fixed_interval", "max_runs", b"max_runs", "start_at", b"start_at", "start_run_request", b"start_run_request"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fixed_interval", b"_fixed_interval"]) -> typing.Literal["fixed_interval"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max_runs", b"_max_runs"]) -> typing.Literal["max_runs"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_start_at", b"_start_at"]) -> typing.Literal["start_at"] | None: ...

global___StartAutomationRequest = StartAutomationRequest

@typing.final
class StartAutomationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTOMATION_ID_FIELD_NUMBER: builtins.int
    SERIES_ID_FIELD_NUMBER: builtins.int
    NEXT_RUN_AT_FIELD_NUMBER: builtins.int
    automation_id: builtins.int
    series_id: builtins.int
    next_run_at: builtins.str
    def __init__(
        self,
        *,
        automation_id: builtins.int = ...,
        series_id: builtins.int = ...,
        next_run_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["automation_id", b"automation_id", "next_run_at", b"next_run_at", "series_id", b"series_id"]) -> None: ...

global___StartAutomationResponse = StartAutomationResponse

@typing.final
class Automation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTOMATION_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    FEDERATION_FIELD_NUMBER: builtins.int
    SERIES_ID_FIELD_NUMBER: builtins.int
    FLWR_AID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    NEXT_RUN_AT_FIELD_NUMBER: builtins.int
    FIXED_INTERVAL_FIELD_NUMBER: builtins.int
    REMAINING_RUNS_FIELD_NUMBER: builtins.int
    STOPPED_AT_FIELD_NUMBER: builtins.int
    automation_id: builtins.int
    status: builtins.str
    federation: builtins.str
    series_id: builtins.int
    flwr_aid: builtins.str
    created_at: builtins.str
    updated_at: builtins.str
    next_run_at: builtins.str
    fixed_interval: builtins.int
    remaining_runs: builtins.int
    stopped_at: builtins.str
    def __init__(
        self,
        *,
        automation_id: builtins.int = ...,
        status: builtins.str = ...,
        federation: builtins.str = ...,
        series_id: builtins.int = ...,
        flwr_aid: builtins.str = ...,
        created_at: builtins.str = ...,
        updated_at: builtins.str = ...,
        next_run_at: builtins.str = ...,
        fixed_interval: builtins.int | None = ...,
        remaining_runs: builtins.int | None = ...,
        stopped_at: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_fixed_interval", b"_fixed_interval", "_remaining_runs", b"_remaining_runs", "_stopped_at", b"_stopped_at", "fixed_interval", b"fixed_interval", "remaining_runs", b"remaining_runs", "stopped_at", b"stopped_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_fixed_interval", b"_fixed_interval", "_remaining_runs", b"_remaining_runs", "_stopped_at", b"_stopped_at", "automation_id", b"automation_id", "created_at", b"created_at", "federation", b"federation", "fixed_interval", b"fixed_interval", "flwr_aid", b"flwr_aid", "next_run_at", b"next_run_at", "remaining_runs", b"remaining_runs", "series_id", b"series_id", "status", b"status", "stopped_at", b"stopped_at", "updated_at", b"updated_at"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fixed_interval", b"_fixed_interval"]) -> typing.Literal["fixed_interval"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_remaining_runs", b"_remaining_runs"]) -> typing.Literal["remaining_runs"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_stopped_at", b"_stopped_at"]) -> typing.Literal["stopped_at"] | None: ...

global___Automation = Automation

@typing.final
class ListAutomationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_FIELD_NUMBER: builtins.int
    federation: builtins.str
    def __init__(
        self,
        *,
        federation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation", b"federation"]) -> None: ...

global___ListAutomationsRequest = ListAutomationsRequest

@typing.final
class ListAutomationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTOMATIONS_FIELD_NUMBER: builtins.int
    @property
    def automations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Automation]: ...
    def __init__(
        self,
        *,
        automations: collections.abc.Iterable[global___Automation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["automations", b"automations"]) -> None: ...

global___ListAutomationsResponse = ListAutomationsResponse

@typing.final
class StopAutomationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTOMATION_ID_FIELD_NUMBER: builtins.int
    automation_id: builtins.int
    def __init__(
        self,
        *,
        automation_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["automation_id", b"automation_id"]) -> None: ...

global___StopAutomationRequest = StopAutomationRequest

@typing.final
class StopAutomationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StopAutomationResponse = StopAutomationResponse

@typing.final
class StreamLogsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    AFTER_TIMESTAMP_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    after_timestamp: builtins.float
    def __init__(
        self,
        *,
        run_id: builtins.int = ...,
        after_timestamp: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["after_timestamp", b"after_timestamp", "run_id", b"run_id"]) -> None: ...

global___StreamLogsRequest = StreamLogsRequest

@typing.final
class StreamLogsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOG_OUTPUT_FIELD_NUMBER: builtins.int
    LATEST_TIMESTAMP_FIELD_NUMBER: builtins.int
    log_output: builtins.str
    latest_timestamp: builtins.float
    def __init__(
        self,
        *,
        log_output: builtins.str = ...,
        latest_timestamp: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["latest_timestamp", b"latest_timestamp", "log_output", b"log_output"]) -> None: ...

global___StreamLogsResponse = StreamLogsResponse

@typing.final
class ListRunsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    limit: builtins.int
    def __init__(
        self,
        *,
        run_id: builtins.int | None = ...,
        limit: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_limit", b"_limit", "_run_id", b"_run_id", "limit", b"limit", "run_id", b"run_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_limit", b"_limit", "_run_id", b"_run_id", "limit", b"limit", "run_id", b"run_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_limit", b"_limit"]) -> typing.Literal["limit"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_run_id", b"_run_id"]) -> typing.Literal["run_id"] | None: ...

global___ListRunsRequest = ListRunsRequest

@typing.final
class ListRunsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class RunDictEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> flwr.proto.run_pb2.Run: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: flwr.proto.run_pb2.Run | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    RUN_DICT_FIELD_NUMBER: builtins.int
    NOW_FIELD_NUMBER: builtins.int
    now: builtins.str
    @property
    def run_dict(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, flwr.proto.run_pb2.Run]: ...
    def __init__(
        self,
        *,
        run_dict: collections.abc.Mapping[builtins.int, flwr.proto.run_pb2.Run] | None = ...,
        now: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["now", b"now", "run_dict", b"run_dict"]) -> None: ...

global___ListRunsResponse = ListRunsResponse

@typing.final
class ListRunSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATED_BEFORE_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    FEDERATION_ID_FIELD_NUMBER: builtins.int
    updated_before: builtins.str
    limit: builtins.int
    federation_id: builtins.str
    def __init__(
        self,
        *,
        updated_before: builtins.str | None = ...,
        limit: builtins.int | None = ...,
        federation_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_federation_id", b"_federation_id", "_limit", b"_limit", "_updated_before", b"_updated_before", "federation_id", b"federation_id", "limit", b"limit", "updated_before", b"updated_before"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_federation_id", b"_federation_id", "_limit", b"_limit", "_updated_before", b"_updated_before", "federation_id", b"federation_id", "limit", b"limit", "updated_before", b"updated_before"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_federation_id", b"_federation_id"]) -> typing.Literal["federation_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_limit", b"_limit"]) -> typing.Literal["limit"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_updated_before", b"_updated_before"]) -> typing.Literal["updated_before"] | None: ...

global___ListRunSeriesRequest = ListRunSeriesRequest

@typing.final
class ListRunSeriesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.runseries_pb2.RunSeries]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[flwr.proto.runseries_pb2.RunSeries] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entries", b"entries"]) -> None: ...

global___ListRunSeriesResponse = ListRunSeriesResponse

@typing.final
class GetRunSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_ID_FIELD_NUMBER: builtins.int
    series_id: builtins.int
    def __init__(
        self,
        *,
        series_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series_id", b"series_id"]) -> None: ...

global___GetRunSeriesRequest = GetRunSeriesRequest

@typing.final
class GetRunSeriesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    @property
    def series(self) -> flwr.proto.runseries_pb2.RunSeries: ...
    @property
    def context(self) -> flwr.proto.message_pb2.Context: ...
    def __init__(
        self,
        *,
        series: flwr.proto.runseries_pb2.RunSeries | None = ...,
        context: flwr.proto.message_pb2.Context | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context", "series", b"series"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "series", b"series"]) -> None: ...

global___GetRunSeriesResponse = GetRunSeriesResponse

@typing.final
class GetLoginDetailsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetLoginDetailsRequest = GetLoginDetailsRequest

@typing.final
class GetLoginDetailsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHN_TYPE_FIELD_NUMBER: builtins.int
    DEVICE_CODE_FIELD_NUMBER: builtins.int
    VERIFICATION_URI_COMPLETE_FIELD_NUMBER: builtins.int
    EXPIRES_IN_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    authn_type: builtins.str
    device_code: builtins.str
    verification_uri_complete: builtins.str
    expires_in: builtins.int
    interval: builtins.int
    def __init__(
        self,
        *,
        authn_type: builtins.str = ...,
        device_code: builtins.str = ...,
        verification_uri_complete: builtins.str = ...,
        expires_in: builtins.int = ...,
        interval: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["authn_type", b"authn_type", "device_code", b"device_code", "expires_in", b"expires_in", "interval", b"interval", "verification_uri_complete", b"verification_uri_complete"]) -> None: ...

global___GetLoginDetailsResponse = GetLoginDetailsResponse

@typing.final
class GetAuthTokensRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEVICE_CODE_FIELD_NUMBER: builtins.int
    device_code: builtins.str
    def __init__(
        self,
        *,
        device_code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["device_code", b"device_code"]) -> None: ...

global___GetAuthTokensRequest = GetAuthTokensRequest

@typing.final
class GetAuthTokensResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    refresh_token: builtins.str
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "refresh_token", b"refresh_token"]) -> None: ...

global___GetAuthTokensResponse = GetAuthTokensResponse

@typing.final
class ListConnectorsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListConnectorsRequest = ListConnectorsRequest

@typing.final
class Connector(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CONNECTED_FIELD_NUMBER: builtins.int
    connector_ref: builtins.str
    display_name: builtins.str
    description: builtins.str
    connected: builtins.bool
    def __init__(
        self,
        *,
        connector_ref: builtins.str = ...,
        display_name: builtins.str = ...,
        description: builtins.str = ...,
        connected: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connected", b"connected", "connector_ref", b"connector_ref", "description", b"description", "display_name", b"display_name"]) -> None: ...

global___Connector = Connector

@typing.final
class ListConnectorsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTORS_FIELD_NUMBER: builtins.int
    @property
    def connectors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Connector]: ...
    def __init__(
        self,
        *,
        connectors: collections.abc.Iterable[global___Connector] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connectors", b"connectors"]) -> None: ...

global___ListConnectorsResponse = ListConnectorsResponse

@typing.final
class DisconnectConnectorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    connector_ref: builtins.str
    def __init__(
        self,
        *,
        connector_ref: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connector_ref", b"connector_ref"]) -> None: ...

global___DisconnectConnectorRequest = DisconnectConnectorRequest

@typing.final
class DisconnectConnectorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DisconnectConnectorResponse = DisconnectConnectorResponse

@typing.final
class BeginConnectorOAuthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    REDIRECT_URI_FIELD_NUMBER: builtins.int
    connector_ref: builtins.str
    redirect_uri: builtins.str
    def __init__(
        self,
        *,
        connector_ref: builtins.str = ...,
        redirect_uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connector_ref", b"connector_ref", "redirect_uri", b"redirect_uri"]) -> None: ...

global___BeginConnectorOAuthRequest = BeginConnectorOAuthRequest

@typing.final
class BeginConnectorOAuthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OAUTH_SESSION_ID_FIELD_NUMBER: builtins.int
    AUTHORIZATION_URL_FIELD_NUMBER: builtins.int
    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    oauth_session_id: builtins.str
    authorization_url: builtins.str
    connector_ref: builtins.str
    expires_at: builtins.str
    def __init__(
        self,
        *,
        oauth_session_id: builtins.str = ...,
        authorization_url: builtins.str = ...,
        connector_ref: builtins.str = ...,
        expires_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["authorization_url", b"authorization_url", "connector_ref", b"connector_ref", "expires_at", b"expires_at", "oauth_session_id", b"oauth_session_id"]) -> None: ...

global___BeginConnectorOAuthResponse = BeginConnectorOAuthResponse

@typing.final
class CompleteConnectorOAuthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OAUTH_SESSION_ID_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    oauth_session_id: builtins.str
    code: builtins.str
    state: builtins.str
    def __init__(
        self,
        *,
        oauth_session_id: builtins.str = ...,
        code: builtins.str = ...,
        state: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "oauth_session_id", b"oauth_session_id", "state", b"state"]) -> None: ...

global___CompleteConnectorOAuthRequest = CompleteConnectorOAuthRequest

@typing.final
class CompleteConnectorOAuthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    connector_ref: builtins.str
    def __init__(
        self,
        *,
        connector_ref: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connector_ref", b"connector_ref"]) -> None: ...

global___CompleteConnectorOAuthResponse = CompleteConnectorOAuthResponse

@typing.final
class StopRunRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    def __init__(
        self,
        *,
        run_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["run_id", b"run_id"]) -> None: ...

global___StopRunRequest = StopRunRequest

@typing.final
class StopRunResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

global___StopRunResponse = StopRunResponse

@typing.final
class PullArtifactsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    def __init__(
        self,
        *,
        run_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["run_id", b"run_id"]) -> None: ...

global___PullArtifactsRequest = PullArtifactsRequest

@typing.final
class PullArtifactsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str
    def __init__(
        self,
        *,
        url: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_url", b"_url", "url", b"url"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_url", b"_url", "url", b"url"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_url", b"_url"]) -> typing.Literal["url"] | None: ...

global___PullArtifactsResponse = PullArtifactsResponse

@typing.final
class RegisterNodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    public_key: builtins.bytes
    def __init__(
        self,
        *,
        public_key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["public_key", b"public_key"]) -> None: ...

global___RegisterNodeRequest = RegisterNodeRequest

@typing.final
class RegisterNodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_node_id", b"_node_id", "node_id", b"node_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_node_id", b"_node_id", "node_id", b"node_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_node_id", b"_node_id"]) -> typing.Literal["node_id"] | None: ...

global___RegisterNodeResponse = RegisterNodeResponse

@typing.final
class UnregisterNodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["node_id", b"node_id"]) -> None: ...

global___UnregisterNodeRequest = UnregisterNodeRequest

@typing.final
class UnregisterNodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UnregisterNodeResponse = UnregisterNodeResponse

@typing.final
class ListNodesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListNodesRequest = ListNodesRequest

@typing.final
class ListNodesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODES_INFO_FIELD_NUMBER: builtins.int
    NOW_FIELD_NUMBER: builtins.int
    now: builtins.str
    @property
    def nodes_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.node_pb2.NodeInfo]: ...
    def __init__(
        self,
        *,
        nodes_info: collections.abc.Iterable[flwr.proto.node_pb2.NodeInfo] | None = ...,
        now: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nodes_info", b"nodes_info", "now", b"now"]) -> None: ...

global___ListNodesResponse = ListNodesResponse

@typing.final
class ListFederationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListFederationsRequest = ListFederationsRequest

@typing.final
class ListFederationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATIONS_FIELD_NUMBER: builtins.int
    @property
    def federations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.federation_pb2.Federation]: ...
    def __init__(
        self,
        *,
        federations: collections.abc.Iterable[flwr.proto.federation_pb2.Federation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federations", b"federations"]) -> None: ...

global___ListFederationsResponse = ListFederationsResponse

@typing.final
class AppInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APP_ID_FIELD_NUMBER: builtins.int
    FAB_HASH_FIELD_NUMBER: builtins.int
    APP_TYPE_FIELD_NUMBER: builtins.int
    app_id: builtins.str
    fab_hash: builtins.str
    app_type: builtins.str
    def __init__(
        self,
        *,
        app_id: builtins.str = ...,
        fab_hash: builtins.str = ...,
        app_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["app_id", b"app_id", "app_type", b"app_type", "fab_hash", b"fab_hash"]) -> None: ...

global___AppInfo = AppInfo

@typing.final
class ListAppsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_ID_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    federation_id: builtins.str
    limit: builtins.int
    def __init__(
        self,
        *,
        federation_id: builtins.str = ...,
        limit: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_limit", b"_limit", "limit", b"limit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_limit", b"_limit", "federation_id", b"federation_id", "limit", b"limit"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_limit", b"_limit"]) -> typing.Literal["limit"] | None: ...

global___ListAppsRequest = ListAppsRequest

@typing.final
class ListAppsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPS_FIELD_NUMBER: builtins.int
    @property
    def apps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AppInfo]: ...
    def __init__(
        self,
        *,
        apps: collections.abc.Iterable[global___AppInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["apps", b"apps"]) -> None: ...

global___ListAppsResponse = ListAppsResponse

@typing.final
class ShowFederationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name"]) -> None: ...

global___ShowFederationRequest = ShowFederationRequest

@typing.final
class ShowFederationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_FIELD_NUMBER: builtins.int
    NOW_FIELD_NUMBER: builtins.int
    now: builtins.str
    @property
    def federation(self) -> flwr.proto.federation_pb2.Federation: ...
    def __init__(
        self,
        *,
        federation: flwr.proto.federation_pb2.Federation | None = ...,
        now: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["federation", b"federation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["federation", b"federation", "now", b"now"]) -> None: ...

global___ShowFederationResponse = ShowFederationResponse

@typing.final
class CreateFederationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    SIMULATION_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    description: builtins.str
    simulation: builtins.bool
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
        description: builtins.str = ...,
        simulation: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "federation_name", b"federation_name", "simulation", b"simulation"]) -> None: ...

global___CreateFederationRequest = CreateFederationRequest

@typing.final
class CreateFederationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_FIELD_NUMBER: builtins.int
    @property
    def federation(self) -> flwr.proto.federation_pb2.Federation: ...
    def __init__(
        self,
        *,
        federation: flwr.proto.federation_pb2.Federation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["federation", b"federation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["federation", b"federation"]) -> None: ...

global___CreateFederationResponse = CreateFederationResponse

@typing.final
class ArchiveFederationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name"]) -> None: ...

global___ArchiveFederationRequest = ArchiveFederationRequest

@typing.final
class ArchiveFederationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ArchiveFederationResponse = ArchiveFederationResponse

@typing.final
class AddNodeToFederationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    node_id: builtins.int
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
        node_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name", "node_id", b"node_id"]) -> None: ...

global___AddNodeToFederationRequest = AddNodeToFederationRequest

@typing.final
class AddNodeToFederationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AddNodeToFederationResponse = AddNodeToFederationResponse

@typing.final
class RemoveNodeFromFederationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    node_id: builtins.int
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
        node_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name", "node_id", b"node_id"]) -> None: ...

global___RemoveNodeFromFederationRequest = RemoveNodeFromFederationRequest

@typing.final
class RemoveNodeFromFederationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RemoveNodeFromFederationResponse = RemoveNodeFromFederationResponse

@typing.final
class RemoveAccountFromFederationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    account_name: builtins.str
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
        account_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_account_name", b"_account_name", "account_name", b"account_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_account_name", b"_account_name", "account_name", b"account_name", "federation_name", b"federation_name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_account_name", b"_account_name"]) -> typing.Literal["account_name"] | None: ...

global___RemoveAccountFromFederationRequest = RemoveAccountFromFederationRequest

@typing.final
class RemoveAccountFromFederationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RemoveAccountFromFederationResponse = RemoveAccountFromFederationResponse

@typing.final
class CreateInvitationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVITEE_ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    invitee_account_name: builtins.str
    federation_name: builtins.str
    def __init__(
        self,
        *,
        invitee_account_name: builtins.str = ...,
        federation_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name", "invitee_account_name", b"invitee_account_name"]) -> None: ...

global___CreateInvitationRequest = CreateInvitationRequest

@typing.final
class CreateInvitationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CreateInvitationResponse = CreateInvitationResponse

@typing.final
class ListInvitationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListInvitationsRequest = ListInvitationsRequest

@typing.final
class ListInvitationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATED_INVITATIONS_FIELD_NUMBER: builtins.int
    RECEIVED_INVITATIONS_FIELD_NUMBER: builtins.int
    @property
    def created_invitations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.federation_pb2.Invitation]: ...
    @property
    def received_invitations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.federation_pb2.Invitation]: ...
    def __init__(
        self,
        *,
        created_invitations: collections.abc.Iterable[flwr.proto.federation_pb2.Invitation] | None = ...,
        received_invitations: collections.abc.Iterable[flwr.proto.federation_pb2.Invitation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_invitations", b"created_invitations", "received_invitations", b"received_invitations"]) -> None: ...

global___ListInvitationsResponse = ListInvitationsResponse

@typing.final
class AcceptInvitationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name"]) -> None: ...

global___AcceptInvitationRequest = AcceptInvitationRequest

@typing.final
class AcceptInvitationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AcceptInvitationResponse = AcceptInvitationResponse

@typing.final
class RejectInvitationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name"]) -> None: ...

global___RejectInvitationRequest = RejectInvitationRequest

@typing.final
class RejectInvitationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RejectInvitationResponse = RejectInvitationResponse

@typing.final
class RevokeInvitationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVITEE_ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    invitee_account_name: builtins.str
    federation_name: builtins.str
    def __init__(
        self,
        *,
        invitee_account_name: builtins.str = ...,
        federation_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name", "invitee_account_name", b"invitee_account_name"]) -> None: ...

global___RevokeInvitationRequest = RevokeInvitationRequest

@typing.final
class RevokeInvitationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RevokeInvitationResponse = RevokeInvitationResponse

@typing.final
class ConfigureSimulationFederationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    @property
    def config(self) -> flwr.proto.federation_config_pb2.SimulationConfig: ...
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
        config: flwr.proto.federation_config_pb2.SimulationConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "federation_name", b"federation_name"]) -> None: ...

global___ConfigureSimulationFederationRequest = ConfigureSimulationFederationRequest

@typing.final
class ConfigureSimulationFederationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEDERATION_NAME_FIELD_NUMBER: builtins.int
    federation_name: builtins.str
    def __init__(
        self,
        *,
        federation_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["federation_name", b"federation_name"]) -> None: ...

global___ConfigureSimulationFederationResponse = ConfigureSimulationFederationResponse

@typing.final
class StreamRunEventsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    AFTER_TASK_EVENT_ID_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    after_task_event_id: builtins.int
    def __init__(
        self,
        *,
        run_id: builtins.int = ...,
        after_task_event_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_after_task_event_id", b"_after_task_event_id", "after_task_event_id", b"after_task_event_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_after_task_event_id", b"_after_task_event_id", "after_task_event_id", b"after_task_event_id", "run_id", b"run_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_after_task_event_id", b"_after_task_event_id"]) -> typing.Literal["after_task_event_id"] | None: ...

global___StreamRunEventsRequest = StreamRunEventsRequest

@typing.final
class StreamRunEventsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_EVENT_FIELD_NUMBER: builtins.int
    @property
    def task_event(self) -> flwr.proto.task_pb2.TaskEvent: ...
    def __init__(
        self,
        *,
        task_event: flwr.proto.task_pb2.TaskEvent | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["task_event", b"task_event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["task_event", b"task_event"]) -> None: ...

global___StreamRunEventsResponse = StreamRunEventsResponse
