"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import abc
import collections.abc
import flwr.proto.control_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class ControlStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    StartRun: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StartRunRequest,
        flwr.proto.control_pb2.StartRunResponse,
    ]
    """Start run upon request"""

    StopRun: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StopRunRequest,
        flwr.proto.control_pb2.StopRunResponse,
    ]
    """Stop run upon request"""

    StartAutomation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StartAutomationRequest,
        flwr.proto.control_pb2.StartAutomationResponse,
    ]
    """Start automation upon request"""

    ListAutomations: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListAutomationsRequest,
        flwr.proto.control_pb2.ListAutomationsResponse,
    ]
    """List automations"""

    StopAutomation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StopAutomationRequest,
        flwr.proto.control_pb2.StopAutomationResponse,
    ]
    """Stop automation"""

    StreamLogs: grpc.UnaryStreamMultiCallable[
        flwr.proto.control_pb2.StreamLogsRequest,
        flwr.proto.control_pb2.StreamLogsResponse,
    ]
    """Start log stream upon request"""

    ListRuns: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListRunsRequest,
        flwr.proto.control_pb2.ListRunsResponse,
    ]
    """flwr ls command"""

    ListRunSeries: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListRunSeriesRequest,
        flwr.proto.control_pb2.ListRunSeriesResponse,
    ]
    """List run series"""

    GetRunSeries: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.GetRunSeriesRequest,
        flwr.proto.control_pb2.GetRunSeriesResponse,
    ]
    """Get run series"""

    GetLoginDetails: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.GetLoginDetailsRequest,
        flwr.proto.control_pb2.GetLoginDetailsResponse,
    ]
    """Get login details upon request"""

    GetAuthTokens: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.GetAuthTokensRequest,
        flwr.proto.control_pb2.GetAuthTokensResponse,
    ]
    """Get auth tokens upon request"""

    ListConnectors: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListConnectorsRequest,
        flwr.proto.control_pb2.ListConnectorsResponse,
    ]
    """List OAuth connectors available to the authenticated account"""

    DisconnectConnector: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.DisconnectConnectorRequest,
        flwr.proto.control_pb2.DisconnectConnectorResponse,
    ]
    """Disconnect connector credentials for the authenticated account"""

    BeginConnectorOAuth: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.BeginConnectorOAuthRequest,
        flwr.proto.control_pb2.BeginConnectorOAuthResponse,
    ]
    """Begin OAuth connector authorization flow"""

    CompleteConnectorOAuth: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.CompleteConnectorOAuthRequest,
        flwr.proto.control_pb2.CompleteConnectorOAuthResponse,
    ]
    """Complete OAuth connector authorization flow"""

    PullArtifacts: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.PullArtifactsRequest,
        flwr.proto.control_pb2.PullArtifactsResponse,
    ]
    """Pull artifacts generated during a run (flwr pull)"""

    RegisterNode: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RegisterNodeRequest,
        flwr.proto.control_pb2.RegisterNodeResponse,
    ]
    """Register SuperNode"""

    UnregisterNode: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.UnregisterNodeRequest,
        flwr.proto.control_pb2.UnregisterNodeResponse,
    ]
    """Unregister SuperNode"""

    ListNodes: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListNodesRequest,
        flwr.proto.control_pb2.ListNodesResponse,
    ]
    """List SuperNodes"""

    ListFederations: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListFederationsRequest,
        flwr.proto.control_pb2.ListFederationsResponse,
    ]
    """List Federations"""

    ListApps: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListAppsRequest,
        flwr.proto.control_pb2.ListAppsResponse,
    ]
    """List Apps in a Federation"""

    ShowFederation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ShowFederationRequest,
        flwr.proto.control_pb2.ShowFederationResponse,
    ]
    """Show Federation"""

    CreateFederation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.CreateFederationRequest,
        flwr.proto.control_pb2.CreateFederationResponse,
    ]
    """Create Federation"""

    ArchiveFederation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ArchiveFederationRequest,
        flwr.proto.control_pb2.ArchiveFederationResponse,
    ]
    """Archive Federation"""

    AddNodeToFederation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.AddNodeToFederationRequest,
        flwr.proto.control_pb2.AddNodeToFederationResponse,
    ]
    """Add SuperNode to Federation"""

    RemoveNodeFromFederation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RemoveNodeFromFederationRequest,
        flwr.proto.control_pb2.RemoveNodeFromFederationResponse,
    ]
    """Remove SuperNode from Federation"""

    RemoveAccountFromFederation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RemoveAccountFromFederationRequest,
        flwr.proto.control_pb2.RemoveAccountFromFederationResponse,
    ]
    """Remove Account from Federation"""

    CreateInvitation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.CreateInvitationRequest,
        flwr.proto.control_pb2.CreateInvitationResponse,
    ]
    """Create Invitation"""

    ListInvitations: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListInvitationsRequest,
        flwr.proto.control_pb2.ListInvitationsResponse,
    ]
    """List Invitations"""

    AcceptInvitation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.AcceptInvitationRequest,
        flwr.proto.control_pb2.AcceptInvitationResponse,
    ]
    """Accept Invitation"""

    RejectInvitation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RejectInvitationRequest,
        flwr.proto.control_pb2.RejectInvitationResponse,
    ]
    """Reject Invitation"""

    RevokeInvitation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RevokeInvitationRequest,
        flwr.proto.control_pb2.RevokeInvitationResponse,
    ]
    """Revoke Invitation"""

    ConfigureSimulationFederation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ConfigureSimulationFederationRequest,
        flwr.proto.control_pb2.ConfigureSimulationFederationResponse,
    ]
    """Set Simulation Configuration"""

    StreamRunEvents: grpc.UnaryStreamMultiCallable[
        flwr.proto.control_pb2.StreamRunEventsRequest,
        flwr.proto.control_pb2.StreamRunEventsResponse,
    ]
    """##############
    Unused for now
    ##############

    Start run event stream
    """

class ControlAsyncStub:
    StartRun: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StartRunRequest,
        flwr.proto.control_pb2.StartRunResponse,
    ]
    """Start run upon request"""

    StopRun: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StopRunRequest,
        flwr.proto.control_pb2.StopRunResponse,
    ]
    """Stop run upon request"""

    StartAutomation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StartAutomationRequest,
        flwr.proto.control_pb2.StartAutomationResponse,
    ]
    """Start automation upon request"""

    ListAutomations: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListAutomationsRequest,
        flwr.proto.control_pb2.ListAutomationsResponse,
    ]
    """List automations"""

    StopAutomation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StopAutomationRequest,
        flwr.proto.control_pb2.StopAutomationResponse,
    ]
    """Stop automation"""

    StreamLogs: grpc.aio.UnaryStreamMultiCallable[
        flwr.proto.control_pb2.StreamLogsRequest,
        flwr.proto.control_pb2.StreamLogsResponse,
    ]
    """Start log stream upon request"""

    ListRuns: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListRunsRequest,
        flwr.proto.control_pb2.ListRunsResponse,
    ]
    """flwr ls command"""

    ListRunSeries: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListRunSeriesRequest,
        flwr.proto.control_pb2.ListRunSeriesResponse,
    ]
    """List run series"""

    GetRunSeries: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.GetRunSeriesRequest,
        flwr.proto.control_pb2.GetRunSeriesResponse,
    ]
    """Get run series"""

    GetLoginDetails: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.GetLoginDetailsRequest,
        flwr.proto.control_pb2.GetLoginDetailsResponse,
    ]
    """Get login details upon request"""

    GetAuthTokens: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.GetAuthTokensRequest,
        flwr.proto.control_pb2.GetAuthTokensResponse,
    ]
    """Get auth tokens upon request"""

    ListConnectors: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListConnectorsRequest,
        flwr.proto.control_pb2.ListConnectorsResponse,
    ]
    """List OAuth connectors available to the authenticated account"""

    DisconnectConnector: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.DisconnectConnectorRequest,
        flwr.proto.control_pb2.DisconnectConnectorResponse,
    ]
    """Disconnect connector credentials for the authenticated account"""

    BeginConnectorOAuth: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.BeginConnectorOAuthRequest,
        flwr.proto.control_pb2.BeginConnectorOAuthResponse,
    ]
    """Begin OAuth connector authorization flow"""

    CompleteConnectorOAuth: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.CompleteConnectorOAuthRequest,
        flwr.proto.control_pb2.CompleteConnectorOAuthResponse,
    ]
    """Complete OAuth connector authorization flow"""

    PullArtifacts: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.PullArtifactsRequest,
        flwr.proto.control_pb2.PullArtifactsResponse,
    ]
    """Pull artifacts generated during a run (flwr pull)"""

    RegisterNode: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RegisterNodeRequest,
        flwr.proto.control_pb2.RegisterNodeResponse,
    ]
    """Register SuperNode"""

    UnregisterNode: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.UnregisterNodeRequest,
        flwr.proto.control_pb2.UnregisterNodeResponse,
    ]
    """Unregister SuperNode"""

    ListNodes: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListNodesRequest,
        flwr.proto.control_pb2.ListNodesResponse,
    ]
    """List SuperNodes"""

    ListFederations: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListFederationsRequest,
        flwr.proto.control_pb2.ListFederationsResponse,
    ]
    """List Federations"""

    ListApps: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListAppsRequest,
        flwr.proto.control_pb2.ListAppsResponse,
    ]
    """List Apps in a Federation"""

    ShowFederation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ShowFederationRequest,
        flwr.proto.control_pb2.ShowFederationResponse,
    ]
    """Show Federation"""

    CreateFederation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.CreateFederationRequest,
        flwr.proto.control_pb2.CreateFederationResponse,
    ]
    """Create Federation"""

    ArchiveFederation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ArchiveFederationRequest,
        flwr.proto.control_pb2.ArchiveFederationResponse,
    ]
    """Archive Federation"""

    AddNodeToFederation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.AddNodeToFederationRequest,
        flwr.proto.control_pb2.AddNodeToFederationResponse,
    ]
    """Add SuperNode to Federation"""

    RemoveNodeFromFederation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RemoveNodeFromFederationRequest,
        flwr.proto.control_pb2.RemoveNodeFromFederationResponse,
    ]
    """Remove SuperNode from Federation"""

    RemoveAccountFromFederation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RemoveAccountFromFederationRequest,
        flwr.proto.control_pb2.RemoveAccountFromFederationResponse,
    ]
    """Remove Account from Federation"""

    CreateInvitation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.CreateInvitationRequest,
        flwr.proto.control_pb2.CreateInvitationResponse,
    ]
    """Create Invitation"""

    ListInvitations: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ListInvitationsRequest,
        flwr.proto.control_pb2.ListInvitationsResponse,
    ]
    """List Invitations"""

    AcceptInvitation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.AcceptInvitationRequest,
        flwr.proto.control_pb2.AcceptInvitationResponse,
    ]
    """Accept Invitation"""

    RejectInvitation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RejectInvitationRequest,
        flwr.proto.control_pb2.RejectInvitationResponse,
    ]
    """Reject Invitation"""

    RevokeInvitation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.RevokeInvitationRequest,
        flwr.proto.control_pb2.RevokeInvitationResponse,
    ]
    """Revoke Invitation"""

    ConfigureSimulationFederation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.ConfigureSimulationFederationRequest,
        flwr.proto.control_pb2.ConfigureSimulationFederationResponse,
    ]
    """Set Simulation Configuration"""

    StreamRunEvents: grpc.aio.UnaryStreamMultiCallable[
        flwr.proto.control_pb2.StreamRunEventsRequest,
        flwr.proto.control_pb2.StreamRunEventsResponse,
    ]
    """##############
    Unused for now
    ##############

    Start run event stream
    """

class ControlServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def StartRun(
        self,
        request: flwr.proto.control_pb2.StartRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.StartRunResponse, collections.abc.Awaitable[flwr.proto.control_pb2.StartRunResponse]]:
        """Start run upon request"""

    @abc.abstractmethod
    def StopRun(
        self,
        request: flwr.proto.control_pb2.StopRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.StopRunResponse, collections.abc.Awaitable[flwr.proto.control_pb2.StopRunResponse]]:
        """Stop run upon request"""

    @abc.abstractmethod
    def StartAutomation(
        self,
        request: flwr.proto.control_pb2.StartAutomationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.StartAutomationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.StartAutomationResponse]]:
        """Start automation upon request"""

    @abc.abstractmethod
    def ListAutomations(
        self,
        request: flwr.proto.control_pb2.ListAutomationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListAutomationsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListAutomationsResponse]]:
        """List automations"""

    @abc.abstractmethod
    def StopAutomation(
        self,
        request: flwr.proto.control_pb2.StopAutomationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.StopAutomationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.StopAutomationResponse]]:
        """Stop automation"""

    @abc.abstractmethod
    def StreamLogs(
        self,
        request: flwr.proto.control_pb2.StreamLogsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flwr.proto.control_pb2.StreamLogsResponse], collections.abc.AsyncIterator[flwr.proto.control_pb2.StreamLogsResponse]]:
        """Start log stream upon request"""

    @abc.abstractmethod
    def ListRuns(
        self,
        request: flwr.proto.control_pb2.ListRunsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListRunsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListRunsResponse]]:
        """flwr ls command"""

    @abc.abstractmethod
    def ListRunSeries(
        self,
        request: flwr.proto.control_pb2.ListRunSeriesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListRunSeriesResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListRunSeriesResponse]]:
        """List run series"""

    @abc.abstractmethod
    def GetRunSeries(
        self,
        request: flwr.proto.control_pb2.GetRunSeriesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.GetRunSeriesResponse, collections.abc.Awaitable[flwr.proto.control_pb2.GetRunSeriesResponse]]:
        """Get run series"""

    @abc.abstractmethod
    def GetLoginDetails(
        self,
        request: flwr.proto.control_pb2.GetLoginDetailsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.GetLoginDetailsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.GetLoginDetailsResponse]]:
        """Get login details upon request"""

    @abc.abstractmethod
    def GetAuthTokens(
        self,
        request: flwr.proto.control_pb2.GetAuthTokensRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.GetAuthTokensResponse, collections.abc.Awaitable[flwr.proto.control_pb2.GetAuthTokensResponse]]:
        """Get auth tokens upon request"""

    @abc.abstractmethod
    def ListConnectors(
        self,
        request: flwr.proto.control_pb2.ListConnectorsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListConnectorsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListConnectorsResponse]]:
        """List OAuth connectors available to the authenticated account"""

    @abc.abstractmethod
    def DisconnectConnector(
        self,
        request: flwr.proto.control_pb2.DisconnectConnectorRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.DisconnectConnectorResponse, collections.abc.Awaitable[flwr.proto.control_pb2.DisconnectConnectorResponse]]:
        """Disconnect connector credentials for the authenticated account"""

    @abc.abstractmethod
    def BeginConnectorOAuth(
        self,
        request: flwr.proto.control_pb2.BeginConnectorOAuthRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.BeginConnectorOAuthResponse, collections.abc.Awaitable[flwr.proto.control_pb2.BeginConnectorOAuthResponse]]:
        """Begin OAuth connector authorization flow"""

    @abc.abstractmethod
    def CompleteConnectorOAuth(
        self,
        request: flwr.proto.control_pb2.CompleteConnectorOAuthRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.CompleteConnectorOAuthResponse, collections.abc.Awaitable[flwr.proto.control_pb2.CompleteConnectorOAuthResponse]]:
        """Complete OAuth connector authorization flow"""

    @abc.abstractmethod
    def PullArtifacts(
        self,
        request: flwr.proto.control_pb2.PullArtifactsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.PullArtifactsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.PullArtifactsResponse]]:
        """Pull artifacts generated during a run (flwr pull)"""

    @abc.abstractmethod
    def RegisterNode(
        self,
        request: flwr.proto.control_pb2.RegisterNodeRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.RegisterNodeResponse, collections.abc.Awaitable[flwr.proto.control_pb2.RegisterNodeResponse]]:
        """Register SuperNode"""

    @abc.abstractmethod
    def UnregisterNode(
        self,
        request: flwr.proto.control_pb2.UnregisterNodeRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.UnregisterNodeResponse, collections.abc.Awaitable[flwr.proto.control_pb2.UnregisterNodeResponse]]:
        """Unregister SuperNode"""

    @abc.abstractmethod
    def ListNodes(
        self,
        request: flwr.proto.control_pb2.ListNodesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListNodesResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListNodesResponse]]:
        """List SuperNodes"""

    @abc.abstractmethod
    def ListFederations(
        self,
        request: flwr.proto.control_pb2.ListFederationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListFederationsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListFederationsResponse]]:
        """List Federations"""

    @abc.abstractmethod
    def ListApps(
        self,
        request: flwr.proto.control_pb2.ListAppsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListAppsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListAppsResponse]]:
        """List Apps in a Federation"""

    @abc.abstractmethod
    def ShowFederation(
        self,
        request: flwr.proto.control_pb2.ShowFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ShowFederationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ShowFederationResponse]]:
        """Show Federation"""

    @abc.abstractmethod
    def CreateFederation(
        self,
        request: flwr.proto.control_pb2.CreateFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.CreateFederationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.CreateFederationResponse]]:
        """Create Federation"""

    @abc.abstractmethod
    def ArchiveFederation(
        self,
        request: flwr.proto.control_pb2.ArchiveFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ArchiveFederationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ArchiveFederationResponse]]:
        """Archive Federation"""

    @abc.abstractmethod
    def AddNodeToFederation(
        self,
        request: flwr.proto.control_pb2.AddNodeToFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.AddNodeToFederationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.AddNodeToFederationResponse]]:
        """Add SuperNode to Federation"""

    @abc.abstractmethod
    def RemoveNodeFromFederation(
        self,
        request: flwr.proto.control_pb2.RemoveNodeFromFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.RemoveNodeFromFederationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.RemoveNodeFromFederationResponse]]:
        """Remove SuperNode from Federation"""

    @abc.abstractmethod
    def RemoveAccountFromFederation(
        self,
        request: flwr.proto.control_pb2.RemoveAccountFromFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.RemoveAccountFromFederationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.RemoveAccountFromFederationResponse]]:
        """Remove Account from Federation"""

    @abc.abstractmethod
    def CreateInvitation(
        self,
        request: flwr.proto.control_pb2.CreateInvitationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.CreateInvitationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.CreateInvitationResponse]]:
        """Create Invitation"""

    @abc.abstractmethod
    def ListInvitations(
        self,
        request: flwr.proto.control_pb2.ListInvitationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ListInvitationsResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ListInvitationsResponse]]:
        """List Invitations"""

    @abc.abstractmethod
    def AcceptInvitation(
        self,
        request: flwr.proto.control_pb2.AcceptInvitationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.AcceptInvitationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.AcceptInvitationResponse]]:
        """Accept Invitation"""

    @abc.abstractmethod
    def RejectInvitation(
        self,
        request: flwr.proto.control_pb2.RejectInvitationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.RejectInvitationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.RejectInvitationResponse]]:
        """Reject Invitation"""

    @abc.abstractmethod
    def RevokeInvitation(
        self,
        request: flwr.proto.control_pb2.RevokeInvitationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.RevokeInvitationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.RevokeInvitationResponse]]:
        """Revoke Invitation"""

    @abc.abstractmethod
    def ConfigureSimulationFederation(
        self,
        request: flwr.proto.control_pb2.ConfigureSimulationFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.ConfigureSimulationFederationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.ConfigureSimulationFederationResponse]]:
        """Set Simulation Configuration"""

    @abc.abstractmethod
    def StreamRunEvents(
        self,
        request: flwr.proto.control_pb2.StreamRunEventsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flwr.proto.control_pb2.StreamRunEventsResponse], collections.abc.AsyncIterator[flwr.proto.control_pb2.StreamRunEventsResponse]]:
        """##############
        Unused for now
        ##############

        Start run event stream
        """

def add_ControlServicer_to_server(servicer: ControlServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
