# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from flwr.proto import control_pb2 as flwr_dot_proto_dot_control__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in flwr/proto/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRun = channel.unary_unary(
                '/flwr.proto.Control/StartRun',
                request_serializer=flwr_dot_proto_dot_control__pb2.StartRunRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.StartRunResponse.FromString,
                _registered_method=True)
        self.StopRun = channel.unary_unary(
                '/flwr.proto.Control/StopRun',
                request_serializer=flwr_dot_proto_dot_control__pb2.StopRunRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.StopRunResponse.FromString,
                _registered_method=True)
        self.StartAutomation = channel.unary_unary(
                '/flwr.proto.Control/StartAutomation',
                request_serializer=flwr_dot_proto_dot_control__pb2.StartAutomationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.StartAutomationResponse.FromString,
                _registered_method=True)
        self.ListAutomations = channel.unary_unary(
                '/flwr.proto.Control/ListAutomations',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListAutomationsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListAutomationsResponse.FromString,
                _registered_method=True)
        self.StopAutomation = channel.unary_unary(
                '/flwr.proto.Control/StopAutomation',
                request_serializer=flwr_dot_proto_dot_control__pb2.StopAutomationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.StopAutomationResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/flwr.proto.Control/StreamLogs',
                request_serializer=flwr_dot_proto_dot_control__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.StreamLogsResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/flwr.proto.Control/ListRuns',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.ListRunSeries = channel.unary_unary(
                '/flwr.proto.Control/ListRunSeries',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListRunSeriesRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListRunSeriesResponse.FromString,
                _registered_method=True)
        self.GetRunSeries = channel.unary_unary(
                '/flwr.proto.Control/GetRunSeries',
                request_serializer=flwr_dot_proto_dot_control__pb2.GetRunSeriesRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.GetRunSeriesResponse.FromString,
                _registered_method=True)
        self.GetLoginDetails = channel.unary_unary(
                '/flwr.proto.Control/GetLoginDetails',
                request_serializer=flwr_dot_proto_dot_control__pb2.GetLoginDetailsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.GetLoginDetailsResponse.FromString,
                _registered_method=True)
        self.GetAuthTokens = channel.unary_unary(
                '/flwr.proto.Control/GetAuthTokens',
                request_serializer=flwr_dot_proto_dot_control__pb2.GetAuthTokensRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.GetAuthTokensResponse.FromString,
                _registered_method=True)
        self.ListConnectors = channel.unary_unary(
                '/flwr.proto.Control/ListConnectors',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListConnectorsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListConnectorsResponse.FromString,
                _registered_method=True)
        self.DisconnectConnector = channel.unary_unary(
                '/flwr.proto.Control/DisconnectConnector',
                request_serializer=flwr_dot_proto_dot_control__pb2.DisconnectConnectorRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.DisconnectConnectorResponse.FromString,
                _registered_method=True)
        self.BeginConnectorOAuth = channel.unary_unary(
                '/flwr.proto.Control/BeginConnectorOAuth',
                request_serializer=flwr_dot_proto_dot_control__pb2.BeginConnectorOAuthRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.BeginConnectorOAuthResponse.FromString,
                _registered_method=True)
        self.CompleteConnectorOAuth = channel.unary_unary(
                '/flwr.proto.Control/CompleteConnectorOAuth',
                request_serializer=flwr_dot_proto_dot_control__pb2.CompleteConnectorOAuthRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.CompleteConnectorOAuthResponse.FromString,
                _registered_method=True)
        self.PullArtifacts = channel.unary_unary(
                '/flwr.proto.Control/PullArtifacts',
                request_serializer=flwr_dot_proto_dot_control__pb2.PullArtifactsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.PullArtifactsResponse.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/flwr.proto.Control/RegisterNode',
                request_serializer=flwr_dot_proto_dot_control__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.UnregisterNode = channel.unary_unary(
                '/flwr.proto.Control/UnregisterNode',
                request_serializer=flwr_dot_proto_dot_control__pb2.UnregisterNodeRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.UnregisterNodeResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/flwr.proto.Control/ListNodes',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.ListFederations = channel.unary_unary(
                '/flwr.proto.Control/ListFederations',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListFederationsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListFederationsResponse.FromString,
                _registered_method=True)
        self.ListApps = channel.unary_unary(
                '/flwr.proto.Control/ListApps',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListAppsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListAppsResponse.FromString,
                _registered_method=True)
        self.ShowFederation = channel.unary_unary(
                '/flwr.proto.Control/ShowFederation',
                request_serializer=flwr_dot_proto_dot_control__pb2.ShowFederationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ShowFederationResponse.FromString,
                _registered_method=True)
        self.CreateFederation = channel.unary_unary(
                '/flwr.proto.Control/CreateFederation',
                request_serializer=flwr_dot_proto_dot_control__pb2.CreateFederationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.CreateFederationResponse.FromString,
                _registered_method=True)
        self.ArchiveFederation = channel.unary_unary(
                '/flwr.proto.Control/ArchiveFederation',
                request_serializer=flwr_dot_proto_dot_control__pb2.ArchiveFederationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ArchiveFederationResponse.FromString,
                _registered_method=True)
        self.AddNodeToFederation = channel.unary_unary(
                '/flwr.proto.Control/AddNodeToFederation',
                request_serializer=flwr_dot_proto_dot_control__pb2.AddNodeToFederationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.AddNodeToFederationResponse.FromString,
                _registered_method=True)
        self.RemoveNodeFromFederation = channel.unary_unary(
                '/flwr.proto.Control/RemoveNodeFromFederation',
                request_serializer=flwr_dot_proto_dot_control__pb2.RemoveNodeFromFederationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.RemoveNodeFromFederationResponse.FromString,
                _registered_method=True)
        self.RemoveAccountFromFederation = channel.unary_unary(
                '/flwr.proto.Control/RemoveAccountFromFederation',
                request_serializer=flwr_dot_proto_dot_control__pb2.RemoveAccountFromFederationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.RemoveAccountFromFederationResponse.FromString,
                _registered_method=True)
        self.CreateInvitation = channel.unary_unary(
                '/flwr.proto.Control/CreateInvitation',
                request_serializer=flwr_dot_proto_dot_control__pb2.CreateInvitationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.CreateInvitationResponse.FromString,
                _registered_method=True)
        self.ListInvitations = channel.unary_unary(
                '/flwr.proto.Control/ListInvitations',
                request_serializer=flwr_dot_proto_dot_control__pb2.ListInvitationsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ListInvitationsResponse.FromString,
                _registered_method=True)
        self.AcceptInvitation = channel.unary_unary(
                '/flwr.proto.Control/AcceptInvitation',
                request_serializer=flwr_dot_proto_dot_control__pb2.AcceptInvitationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.AcceptInvitationResponse.FromString,
                _registered_method=True)
        self.RejectInvitation = channel.unary_unary(
                '/flwr.proto.Control/RejectInvitation',
                request_serializer=flwr_dot_proto_dot_control__pb2.RejectInvitationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.RejectInvitationResponse.FromString,
                _registered_method=True)
        self.RevokeInvitation = channel.unary_unary(
                '/flwr.proto.Control/RevokeInvitation',
                request_serializer=flwr_dot_proto_dot_control__pb2.RevokeInvitationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.RevokeInvitationResponse.FromString,
                _registered_method=True)
        self.ConfigureSimulationFederation = channel.unary_unary(
                '/flwr.proto.Control/ConfigureSimulationFederation',
                request_serializer=flwr_dot_proto_dot_control__pb2.ConfigureSimulationFederationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.ConfigureSimulationFederationResponse.FromString,
                _registered_method=True)
        self.StreamRunEvents = channel.unary_stream(
                '/flwr.proto.Control/StreamRunEvents',
                request_serializer=flwr_dot_proto_dot_control__pb2.StreamRunEventsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.StreamRunEventsResponse.FromString,
                _registered_method=True)


class ControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartRun(self, request, context):
        """Start run upon request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRun(self, request, context):
        """Stop run upon request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAutomation(self, request, context):
        """Start automation upon request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAutomations(self, request, context):
        """List automations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAutomation(self, request, context):
        """Stop automation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Start log stream upon request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """flwr ls command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunSeries(self, request, context):
        """List run series
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunSeries(self, request, context):
        """Get run series
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoginDetails(self, request, context):
        """Get login details upon request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthTokens(self, request, context):
        """Get auth tokens upon request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnectors(self, request, context):
        """List OAuth connectors available to the authenticated account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectConnector(self, request, context):
        """Disconnect connector credentials for the authenticated account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginConnectorOAuth(self, request, context):
        """Begin OAuth connector authorization flow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteConnectorOAuth(self, request, context):
        """Complete OAuth connector authorization flow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullArtifacts(self, request, context):
        """Pull artifacts generated during a run (flwr pull)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Register SuperNode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterNode(self, request, context):
        """Unregister SuperNode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """List SuperNodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFederations(self, request, context):
        """List Federations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApps(self, request, context):
        """List Apps in a Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowFederation(self, request, context):
        """Show Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFederation(self, request, context):
        """Create Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveFederation(self, request, context):
        """Archive Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNodeToFederation(self, request, context):
        """Add SuperNode to Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNodeFromFederation(self, request, context):
        """Remove SuperNode from Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAccountFromFederation(self, request, context):
        """Remove Account from Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInvitation(self, request, context):
        """Create Invitation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInvitations(self, request, context):
        """List Invitations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptInvitation(self, request, context):
        """Accept Invitation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectInvitation(self, request, context):
        """Reject Invitation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeInvitation(self, request, context):
        """Revoke Invitation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureSimulationFederation(self, request, context):
        """Set Simulation Configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRunEvents(self, request, context):
        """##############
        Unused for now
        ##############

        Start run event stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.StartRunRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.StartRunResponse.SerializeToString,
            ),
            'StopRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRun,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.StopRunRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.StopRunResponse.SerializeToString,
            ),
            'StartAutomation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAutomation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.StartAutomationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.StartAutomationResponse.SerializeToString,
            ),
            'ListAutomations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAutomations,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListAutomationsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListAutomationsResponse.SerializeToString,
            ),
            'StopAutomation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAutomation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.StopAutomationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.StopAutomationResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.StreamLogsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.StreamLogsResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListRunsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListRunsResponse.SerializeToString,
            ),
            'ListRunSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunSeries,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListRunSeriesRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListRunSeriesResponse.SerializeToString,
            ),
            'GetRunSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunSeries,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.GetRunSeriesRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.GetRunSeriesResponse.SerializeToString,
            ),
            'GetLoginDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoginDetails,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.GetLoginDetailsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.GetLoginDetailsResponse.SerializeToString,
            ),
            'GetAuthTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthTokens,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.GetAuthTokensRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.GetAuthTokensResponse.SerializeToString,
            ),
            'ListConnectors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectors,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListConnectorsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListConnectorsResponse.SerializeToString,
            ),
            'DisconnectConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectConnector,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.DisconnectConnectorRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.DisconnectConnectorResponse.SerializeToString,
            ),
            'BeginConnectorOAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginConnectorOAuth,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.BeginConnectorOAuthRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.BeginConnectorOAuthResponse.SerializeToString,
            ),
            'CompleteConnectorOAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteConnectorOAuth,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.CompleteConnectorOAuthRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.CompleteConnectorOAuthResponse.SerializeToString,
            ),
            'PullArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.PullArtifacts,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.PullArtifactsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.PullArtifactsResponse.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.RegisterNodeRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'UnregisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterNode,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.UnregisterNodeRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.UnregisterNodeResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListNodesRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListNodesResponse.SerializeToString,
            ),
            'ListFederations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFederations,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListFederationsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListFederationsResponse.SerializeToString,
            ),
            'ListApps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApps,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListAppsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListAppsResponse.SerializeToString,
            ),
            'ShowFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowFederation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ShowFederationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ShowFederationResponse.SerializeToString,
            ),
            'CreateFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFederation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.CreateFederationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.CreateFederationResponse.SerializeToString,
            ),
            'ArchiveFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveFederation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ArchiveFederationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ArchiveFederationResponse.SerializeToString,
            ),
            'AddNodeToFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNodeToFederation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.AddNodeToFederationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.AddNodeToFederationResponse.SerializeToString,
            ),
            'RemoveNodeFromFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNodeFromFederation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.RemoveNodeFromFederationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.RemoveNodeFromFederationResponse.SerializeToString,
            ),
            'RemoveAccountFromFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAccountFromFederation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.RemoveAccountFromFederationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.RemoveAccountFromFederationResponse.SerializeToString,
            ),
            'CreateInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvitation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.CreateInvitationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.CreateInvitationResponse.SerializeToString,
            ),
            'ListInvitations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInvitations,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ListInvitationsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ListInvitationsResponse.SerializeToString,
            ),
            'AcceptInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptInvitation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.AcceptInvitationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.AcceptInvitationResponse.SerializeToString,
            ),
            'RejectInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectInvitation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.RejectInvitationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.RejectInvitationResponse.SerializeToString,
            ),
            'RevokeInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeInvitation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.RevokeInvitationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.RevokeInvitationResponse.SerializeToString,
            ),
            'ConfigureSimulationFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureSimulationFederation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.ConfigureSimulationFederationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.ConfigureSimulationFederationResponse.SerializeToString,
            ),
            'StreamRunEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRunEvents,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.StreamRunEventsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.StreamRunEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flwr.proto.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flwr.proto.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/StartRun',
            flwr_dot_proto_dot_control__pb2.StartRunRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.StartRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/StopRun',
            flwr_dot_proto_dot_control__pb2.StopRunRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.StopRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAutomation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/StartAutomation',
            flwr_dot_proto_dot_control__pb2.StartAutomationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.StartAutomationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAutomations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListAutomations',
            flwr_dot_proto_dot_control__pb2.ListAutomationsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListAutomationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAutomation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/StopAutomation',
            flwr_dot_proto_dot_control__pb2.StopAutomationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.StopAutomationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flwr.proto.Control/StreamLogs',
            flwr_dot_proto_dot_control__pb2.StreamLogsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.StreamLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListRuns',
            flwr_dot_proto_dot_control__pb2.ListRunsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListRunSeries',
            flwr_dot_proto_dot_control__pb2.ListRunSeriesRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListRunSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/GetRunSeries',
            flwr_dot_proto_dot_control__pb2.GetRunSeriesRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.GetRunSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoginDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/GetLoginDetails',
            flwr_dot_proto_dot_control__pb2.GetLoginDetailsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.GetLoginDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/GetAuthTokens',
            flwr_dot_proto_dot_control__pb2.GetAuthTokensRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.GetAuthTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConnectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListConnectors',
            flwr_dot_proto_dot_control__pb2.ListConnectorsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListConnectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/DisconnectConnector',
            flwr_dot_proto_dot_control__pb2.DisconnectConnectorRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.DisconnectConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginConnectorOAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/BeginConnectorOAuth',
            flwr_dot_proto_dot_control__pb2.BeginConnectorOAuthRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.BeginConnectorOAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteConnectorOAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/CompleteConnectorOAuth',
            flwr_dot_proto_dot_control__pb2.CompleteConnectorOAuthRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.CompleteConnectorOAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/PullArtifacts',
            flwr_dot_proto_dot_control__pb2.PullArtifactsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.PullArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/RegisterNode',
            flwr_dot_proto_dot_control__pb2.RegisterNodeRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/UnregisterNode',
            flwr_dot_proto_dot_control__pb2.UnregisterNodeRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.UnregisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListNodes',
            flwr_dot_proto_dot_control__pb2.ListNodesRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFederations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListFederations',
            flwr_dot_proto_dot_control__pb2.ListFederationsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListFederationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListApps',
            flwr_dot_proto_dot_control__pb2.ListAppsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListAppsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ShowFederation',
            flwr_dot_proto_dot_control__pb2.ShowFederationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ShowFederationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/CreateFederation',
            flwr_dot_proto_dot_control__pb2.CreateFederationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.CreateFederationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ArchiveFederation',
            flwr_dot_proto_dot_control__pb2.ArchiveFederationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ArchiveFederationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNodeToFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/AddNodeToFederation',
            flwr_dot_proto_dot_control__pb2.AddNodeToFederationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.AddNodeToFederationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNodeFromFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/RemoveNodeFromFederation',
            flwr_dot_proto_dot_control__pb2.RemoveNodeFromFederationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.RemoveNodeFromFederationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAccountFromFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/RemoveAccountFromFederation',
            flwr_dot_proto_dot_control__pb2.RemoveAccountFromFederationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.RemoveAccountFromFederationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/CreateInvitation',
            flwr_dot_proto_dot_control__pb2.CreateInvitationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.CreateInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInvitations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ListInvitations',
            flwr_dot_proto_dot_control__pb2.ListInvitationsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ListInvitationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/AcceptInvitation',
            flwr_dot_proto_dot_control__pb2.AcceptInvitationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.AcceptInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/RejectInvitation',
            flwr_dot_proto_dot_control__pb2.RejectInvitationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.RejectInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/RevokeInvitation',
            flwr_dot_proto_dot_control__pb2.RevokeInvitationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.RevokeInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureSimulationFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Control/ConfigureSimulationFederation',
            flwr_dot_proto_dot_control__pb2.ConfigureSimulationFederationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.ConfigureSimulationFederationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRunEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flwr.proto.Control/StreamRunEvents',
            flwr_dot_proto_dot_control__pb2.StreamRunEventsRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.StreamRunEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
