"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import collections.abc
import flwr.proto.node_pb2
import flwr.proto.transport_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Run(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class OverrideConfigEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> flwr.proto.transport_pb2.Scalar: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: flwr.proto.transport_pb2.Scalar | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    RUN_ID_FIELD_NUMBER: builtins.int
    FAB_ID_FIELD_NUMBER: builtins.int
    FAB_VERSION_FIELD_NUMBER: builtins.int
    OVERRIDE_CONFIG_FIELD_NUMBER: builtins.int
    FAB_HASH_FIELD_NUMBER: builtins.int
    PENDING_AT_FIELD_NUMBER: builtins.int
    STARTING_AT_FIELD_NUMBER: builtins.int
    RUNNING_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    FLWR_AID_FIELD_NUMBER: builtins.int
    FEDERATION_FIELD_NUMBER: builtins.int
    BYTES_SENT_FIELD_NUMBER: builtins.int
    BYTES_RECV_FIELD_NUMBER: builtins.int
    CLIENTAPP_RUNTIME_FIELD_NUMBER: builtins.int
    PRIMARY_TASK_TYPE_FIELD_NUMBER: builtins.int
    PRIMARY_TASK_ID_FIELD_NUMBER: builtins.int
    SERIES_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    fab_id: builtins.str
    fab_version: builtins.str
    fab_hash: builtins.str
    pending_at: builtins.str
    starting_at: builtins.str
    running_at: builtins.str
    finished_at: builtins.str
    flwr_aid: builtins.str
    federation: builtins.str
    bytes_sent: builtins.int
    bytes_recv: builtins.int
    clientapp_runtime: builtins.float
    primary_task_type: builtins.str
    primary_task_id: builtins.int
    series_id: builtins.int
    account_name: builtins.str
    @property
    def override_config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, flwr.proto.transport_pb2.Scalar]: ...
    @property
    def status(self) -> global___RunStatus: ...
    def __init__(
        self,
        *,
        run_id: builtins.int = ...,
        fab_id: builtins.str = ...,
        fab_version: builtins.str = ...,
        override_config: collections.abc.Mapping[builtins.str, flwr.proto.transport_pb2.Scalar] | None = ...,
        fab_hash: builtins.str = ...,
        pending_at: builtins.str = ...,
        starting_at: builtins.str = ...,
        running_at: builtins.str = ...,
        finished_at: builtins.str = ...,
        status: global___RunStatus | None = ...,
        flwr_aid: builtins.str = ...,
        federation: builtins.str = ...,
        bytes_sent: builtins.int = ...,
        bytes_recv: builtins.int = ...,
        clientapp_runtime: builtins.float = ...,
        primary_task_type: builtins.str = ...,
        primary_task_id: builtins.int | None = ...,
        series_id: builtins.int = ...,
        account_name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_primary_task_id", b"_primary_task_id", "primary_task_id", b"primary_task_id", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_primary_task_id", b"_primary_task_id", "account_name", b"account_name", "bytes_recv", b"bytes_recv", "bytes_sent", b"bytes_sent", "clientapp_runtime", b"clientapp_runtime", "fab_hash", b"fab_hash", "fab_id", b"fab_id", "fab_version", b"fab_version", "federation", b"federation", "finished_at", b"finished_at", "flwr_aid", b"flwr_aid", "override_config", b"override_config", "pending_at", b"pending_at", "primary_task_id", b"primary_task_id", "primary_task_type", b"primary_task_type", "run_id", b"run_id", "running_at", b"running_at", "series_id", b"series_id", "starting_at", b"starting_at", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_primary_task_id", b"_primary_task_id"]) -> typing.Literal["primary_task_id"] | None: ...

global___Run = Run

@typing.final
class RunStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    SUB_STATUS_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    status: builtins.str
    """"starting", "running", "finished" """
    sub_status: builtins.str
    """"completed", "failed", "stopped" or "" (non-finished)"""
    details: builtins.str
    """failure details"""
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        sub_status: builtins.str = ...,
        details: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["details", b"details", "status", b"status", "sub_status", b"sub_status"]) -> None: ...

global___RunStatus = RunStatus

@typing.final
class GetRunRequest(google.protobuf.message.Message):
    """GetRun"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    @property
    def node(self) -> flwr.proto.node_pb2.Node: ...
    def __init__(
        self,
        *,
        node: flwr.proto.node_pb2.Node | None = ...,
        run_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["node", b"node"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["node", b"node", "run_id", b"run_id"]) -> None: ...

global___GetRunRequest = GetRunRequest

@typing.final
class GetRunResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    @property
    def run(self) -> global___Run: ...
    def __init__(
        self,
        *,
        run: global___Run | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["run", b"run"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["run", b"run"]) -> None: ...

global___GetRunResponse = GetRunResponse
