"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import collections.abc
import flwr.proto.run_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RunSeries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_ID_FIELD_NUMBER: builtins.int
    FEDERATION_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    LAST_RUN_STATUS_FIELD_NUMBER: builtins.int
    RUN_IDS_FIELD_NUMBER: builtins.int
    series_id: builtins.int
    federation: builtins.str
    description: builtins.str
    created_at: builtins.str
    updated_at: builtins.str
    @property
    def last_run_status(self) -> flwr.proto.run_pb2.RunStatus: ...
    @property
    def run_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        series_id: builtins.int = ...,
        federation: builtins.str = ...,
        description: builtins.str = ...,
        created_at: builtins.str = ...,
        updated_at: builtins.str = ...,
        last_run_status: flwr.proto.run_pb2.RunStatus | None = ...,
        run_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["last_run_status", b"last_run_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "description", b"description", "federation", b"federation", "last_run_status", b"last_run_status", "run_ids", b"run_ids", "series_id", b"series_id", "updated_at", b"updated_at"]) -> None: ...

global___RunSeries = RunSeries
