"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import abc
import collections.abc
import flwr.proto.control_pb2
import flwr.proto.log_pb2
import flwr.proto.message_pb2
import flwr.proto.run_pb2
import flwr.proto.runtime_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class RuntimeStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    PullPendingTasks: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullPendingTasksRequest,
        flwr.proto.runtime_pb2.PullPendingTasksResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    General Runtime endpoints for SuperExec processes
    ///////////////////////////////////////////////////////////////////////////

    Pull pending tasks
    """

    ClaimTask: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.ClaimTaskRequest,
        flwr.proto.runtime_pb2.ClaimTaskResponse,
    ]
    """Claim task"""

    GetRun: grpc.UnaryUnaryMultiCallable[
        flwr.proto.run_pb2.GetRunRequest,
        flwr.proto.run_pb2.GetRunResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    General Runtime endpoints for App Executor processes
    ///////////////////////////////////////////////////////////////////////////

    Get run details
    """

    SendTaskHeartbeat: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.SendTaskHeartbeatRequest,
        flwr.proto.runtime_pb2.SendTaskHeartbeatResponse,
    ]
    """Task heartbeat"""

    PullTaskInput: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullTaskInputRequest,
        flwr.proto.runtime_pb2.PullTaskInputResponse,
    ]
    """Pull task inputs"""

    PushTaskOutput: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushTaskOutputRequest,
        flwr.proto.runtime_pb2.PushTaskOutputResponse,
    ]
    """Push task outputs"""

    PushObject: grpc.UnaryUnaryMultiCallable[
        flwr.proto.message_pb2.PushObjectRequest,
        flwr.proto.message_pb2.PushObjectResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    Object and task endpoints
    ///////////////////////////////////////////////////////////////////////////

    Push Object
    """

    PullObject: grpc.UnaryUnaryMultiCallable[
        flwr.proto.message_pb2.PullObjectRequest,
        flwr.proto.message_pb2.PullObjectResponse,
    ]
    """Pull Object"""

    ConfirmMessageReceived: grpc.UnaryUnaryMultiCallable[
        flwr.proto.message_pb2.ConfirmMessageReceivedRequest,
        flwr.proto.message_pb2.ConfirmMessageReceivedResponse,
    ]
    """Confirm Message Received"""

    CreateTask: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.CreateTaskRequest,
        flwr.proto.runtime_pb2.CreateTaskResponse,
    ]
    """Create a task"""

    StartAutomation: grpc.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StartAutomationRequest,
        flwr.proto.control_pb2.StartAutomationResponse,
    ]
    """Start an automation"""

    PushTaskMessage: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushTaskMessageRequest,
        flwr.proto.runtime_pb2.PushTaskMessageResponse,
    ]
    """Push task message"""

    PushTaskEvents: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushTaskEventsRequest,
        flwr.proto.runtime_pb2.PushTaskEventsResponse,
    ]
    """Push task events"""

    PullTaskMessage: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullTaskMessageRequest,
        flwr.proto.runtime_pb2.PullTaskMessageResponse,
    ]
    """Pull task messages"""

    RecordTaskUsage: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.RecordTaskUsageRequest,
        flwr.proto.runtime_pb2.RecordTaskUsageResponse,
    ]
    """Record task usage"""

    GetConnector: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.GetConnectorRequest,
        flwr.proto.runtime_pb2.GetConnectorResponse,
    ]
    """Resolve credentials for the authenticated connector task"""

    PushLogs: grpc.UnaryUnaryMultiCallable[
        flwr.proto.log_pb2.PushLogsRequest,
        flwr.proto.log_pb2.PushLogsResponse,
    ]
    """Push task logs"""

    PushMessages: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushAppMessagesRequest,
        flwr.proto.runtime_pb2.PushAppMessagesResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    Message and node endpoints
    ///////////////////////////////////////////////////////////////////////////

    Push messages
    """

    PullMessages: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullAppMessagesRequest,
        flwr.proto.runtime_pb2.PullAppMessagesResponse,
    ]
    """Pull messages"""

    GetNodes: grpc.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.GetNodesRequest,
        flwr.proto.runtime_pb2.GetNodesResponse,
    ]
    """Return a set of nodes"""

class RuntimeAsyncStub:
    PullPendingTasks: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullPendingTasksRequest,
        flwr.proto.runtime_pb2.PullPendingTasksResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    General Runtime endpoints for SuperExec processes
    ///////////////////////////////////////////////////////////////////////////

    Pull pending tasks
    """

    ClaimTask: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.ClaimTaskRequest,
        flwr.proto.runtime_pb2.ClaimTaskResponse,
    ]
    """Claim task"""

    GetRun: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.run_pb2.GetRunRequest,
        flwr.proto.run_pb2.GetRunResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    General Runtime endpoints for App Executor processes
    ///////////////////////////////////////////////////////////////////////////

    Get run details
    """

    SendTaskHeartbeat: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.SendTaskHeartbeatRequest,
        flwr.proto.runtime_pb2.SendTaskHeartbeatResponse,
    ]
    """Task heartbeat"""

    PullTaskInput: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullTaskInputRequest,
        flwr.proto.runtime_pb2.PullTaskInputResponse,
    ]
    """Pull task inputs"""

    PushTaskOutput: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushTaskOutputRequest,
        flwr.proto.runtime_pb2.PushTaskOutputResponse,
    ]
    """Push task outputs"""

    PushObject: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.message_pb2.PushObjectRequest,
        flwr.proto.message_pb2.PushObjectResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    Object and task endpoints
    ///////////////////////////////////////////////////////////////////////////

    Push Object
    """

    PullObject: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.message_pb2.PullObjectRequest,
        flwr.proto.message_pb2.PullObjectResponse,
    ]
    """Pull Object"""

    ConfirmMessageReceived: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.message_pb2.ConfirmMessageReceivedRequest,
        flwr.proto.message_pb2.ConfirmMessageReceivedResponse,
    ]
    """Confirm Message Received"""

    CreateTask: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.CreateTaskRequest,
        flwr.proto.runtime_pb2.CreateTaskResponse,
    ]
    """Create a task"""

    StartAutomation: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.control_pb2.StartAutomationRequest,
        flwr.proto.control_pb2.StartAutomationResponse,
    ]
    """Start an automation"""

    PushTaskMessage: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushTaskMessageRequest,
        flwr.proto.runtime_pb2.PushTaskMessageResponse,
    ]
    """Push task message"""

    PushTaskEvents: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushTaskEventsRequest,
        flwr.proto.runtime_pb2.PushTaskEventsResponse,
    ]
    """Push task events"""

    PullTaskMessage: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullTaskMessageRequest,
        flwr.proto.runtime_pb2.PullTaskMessageResponse,
    ]
    """Pull task messages"""

    RecordTaskUsage: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.RecordTaskUsageRequest,
        flwr.proto.runtime_pb2.RecordTaskUsageResponse,
    ]
    """Record task usage"""

    GetConnector: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.GetConnectorRequest,
        flwr.proto.runtime_pb2.GetConnectorResponse,
    ]
    """Resolve credentials for the authenticated connector task"""

    PushLogs: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.log_pb2.PushLogsRequest,
        flwr.proto.log_pb2.PushLogsResponse,
    ]
    """Push task logs"""

    PushMessages: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PushAppMessagesRequest,
        flwr.proto.runtime_pb2.PushAppMessagesResponse,
    ]
    """///////////////////////////////////////////////////////////////////////////
    Message and node endpoints
    ///////////////////////////////////////////////////////////////////////////

    Push messages
    """

    PullMessages: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.PullAppMessagesRequest,
        flwr.proto.runtime_pb2.PullAppMessagesResponse,
    ]
    """Pull messages"""

    GetNodes: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.runtime_pb2.GetNodesRequest,
        flwr.proto.runtime_pb2.GetNodesResponse,
    ]
    """Return a set of nodes"""

class RuntimeServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def PullPendingTasks(
        self,
        request: flwr.proto.runtime_pb2.PullPendingTasksRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PullPendingTasksResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PullPendingTasksResponse]]:
        """///////////////////////////////////////////////////////////////////////////
        General Runtime endpoints for SuperExec processes
        ///////////////////////////////////////////////////////////////////////////

        Pull pending tasks
        """

    @abc.abstractmethod
    def ClaimTask(
        self,
        request: flwr.proto.runtime_pb2.ClaimTaskRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.ClaimTaskResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.ClaimTaskResponse]]:
        """Claim task"""

    @abc.abstractmethod
    def GetRun(
        self,
        request: flwr.proto.run_pb2.GetRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.run_pb2.GetRunResponse, collections.abc.Awaitable[flwr.proto.run_pb2.GetRunResponse]]:
        """///////////////////////////////////////////////////////////////////////////
        General Runtime endpoints for App Executor processes
        ///////////////////////////////////////////////////////////////////////////

        Get run details
        """

    @abc.abstractmethod
    def SendTaskHeartbeat(
        self,
        request: flwr.proto.runtime_pb2.SendTaskHeartbeatRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.SendTaskHeartbeatResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.SendTaskHeartbeatResponse]]:
        """Task heartbeat"""

    @abc.abstractmethod
    def PullTaskInput(
        self,
        request: flwr.proto.runtime_pb2.PullTaskInputRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PullTaskInputResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PullTaskInputResponse]]:
        """Pull task inputs"""

    @abc.abstractmethod
    def PushTaskOutput(
        self,
        request: flwr.proto.runtime_pb2.PushTaskOutputRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PushTaskOutputResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PushTaskOutputResponse]]:
        """Push task outputs"""

    @abc.abstractmethod
    def PushObject(
        self,
        request: flwr.proto.message_pb2.PushObjectRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.message_pb2.PushObjectResponse, collections.abc.Awaitable[flwr.proto.message_pb2.PushObjectResponse]]:
        """///////////////////////////////////////////////////////////////////////////
        Object and task endpoints
        ///////////////////////////////////////////////////////////////////////////

        Push Object
        """

    @abc.abstractmethod
    def PullObject(
        self,
        request: flwr.proto.message_pb2.PullObjectRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.message_pb2.PullObjectResponse, collections.abc.Awaitable[flwr.proto.message_pb2.PullObjectResponse]]:
        """Pull Object"""

    @abc.abstractmethod
    def ConfirmMessageReceived(
        self,
        request: flwr.proto.message_pb2.ConfirmMessageReceivedRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.message_pb2.ConfirmMessageReceivedResponse, collections.abc.Awaitable[flwr.proto.message_pb2.ConfirmMessageReceivedResponse]]:
        """Confirm Message Received"""

    @abc.abstractmethod
    def CreateTask(
        self,
        request: flwr.proto.runtime_pb2.CreateTaskRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.CreateTaskResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.CreateTaskResponse]]:
        """Create a task"""

    @abc.abstractmethod
    def StartAutomation(
        self,
        request: flwr.proto.control_pb2.StartAutomationRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.control_pb2.StartAutomationResponse, collections.abc.Awaitable[flwr.proto.control_pb2.StartAutomationResponse]]:
        """Start an automation"""

    @abc.abstractmethod
    def PushTaskMessage(
        self,
        request: flwr.proto.runtime_pb2.PushTaskMessageRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PushTaskMessageResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PushTaskMessageResponse]]:
        """Push task message"""

    @abc.abstractmethod
    def PushTaskEvents(
        self,
        request: flwr.proto.runtime_pb2.PushTaskEventsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PushTaskEventsResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PushTaskEventsResponse]]:
        """Push task events"""

    @abc.abstractmethod
    def PullTaskMessage(
        self,
        request: flwr.proto.runtime_pb2.PullTaskMessageRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PullTaskMessageResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PullTaskMessageResponse]]:
        """Pull task messages"""

    @abc.abstractmethod
    def RecordTaskUsage(
        self,
        request: flwr.proto.runtime_pb2.RecordTaskUsageRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.RecordTaskUsageResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.RecordTaskUsageResponse]]:
        """Record task usage"""

    @abc.abstractmethod
    def GetConnector(
        self,
        request: flwr.proto.runtime_pb2.GetConnectorRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.GetConnectorResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.GetConnectorResponse]]:
        """Resolve credentials for the authenticated connector task"""

    @abc.abstractmethod
    def PushLogs(
        self,
        request: flwr.proto.log_pb2.PushLogsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.log_pb2.PushLogsResponse, collections.abc.Awaitable[flwr.proto.log_pb2.PushLogsResponse]]:
        """Push task logs"""

    @abc.abstractmethod
    def PushMessages(
        self,
        request: flwr.proto.runtime_pb2.PushAppMessagesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PushAppMessagesResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PushAppMessagesResponse]]:
        """///////////////////////////////////////////////////////////////////////////
        Message and node endpoints
        ///////////////////////////////////////////////////////////////////////////

        Push messages
        """

    @abc.abstractmethod
    def PullMessages(
        self,
        request: flwr.proto.runtime_pb2.PullAppMessagesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.PullAppMessagesResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.PullAppMessagesResponse]]:
        """Pull messages"""

    @abc.abstractmethod
    def GetNodes(
        self,
        request: flwr.proto.runtime_pb2.GetNodesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.runtime_pb2.GetNodesResponse, collections.abc.Awaitable[flwr.proto.runtime_pb2.GetNodesResponse]]:
        """Return a set of nodes"""

def add_RuntimeServicer_to_server(servicer: RuntimeServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
