# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from flwr.proto import control_pb2 as flwr_dot_proto_dot_control__pb2
from flwr.proto import log_pb2 as flwr_dot_proto_dot_log__pb2
from flwr.proto import message_pb2 as flwr_dot_proto_dot_message__pb2
from flwr.proto import run_pb2 as flwr_dot_proto_dot_run__pb2
from flwr.proto import runtime_pb2 as flwr_dot_proto_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in flwr/proto/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullPendingTasks = channel.unary_unary(
                '/flwr.proto.Runtime/PullPendingTasks',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PullPendingTasksRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PullPendingTasksResponse.FromString,
                _registered_method=True)
        self.ClaimTask = channel.unary_unary(
                '/flwr.proto.Runtime/ClaimTask',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.ClaimTaskRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.ClaimTaskResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/flwr.proto.Runtime/GetRun',
                request_serializer=flwr_dot_proto_dot_run__pb2.GetRunRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_run__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.SendTaskHeartbeat = channel.unary_unary(
                '/flwr.proto.Runtime/SendTaskHeartbeat',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.SendTaskHeartbeatRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.SendTaskHeartbeatResponse.FromString,
                _registered_method=True)
        self.PullTaskInput = channel.unary_unary(
                '/flwr.proto.Runtime/PullTaskInput',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PullTaskInputRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PullTaskInputResponse.FromString,
                _registered_method=True)
        self.PushTaskOutput = channel.unary_unary(
                '/flwr.proto.Runtime/PushTaskOutput',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PushTaskOutputRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PushTaskOutputResponse.FromString,
                _registered_method=True)
        self.PushObject = channel.unary_unary(
                '/flwr.proto.Runtime/PushObject',
                request_serializer=flwr_dot_proto_dot_message__pb2.PushObjectRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_message__pb2.PushObjectResponse.FromString,
                _registered_method=True)
        self.PullObject = channel.unary_unary(
                '/flwr.proto.Runtime/PullObject',
                request_serializer=flwr_dot_proto_dot_message__pb2.PullObjectRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_message__pb2.PullObjectResponse.FromString,
                _registered_method=True)
        self.ConfirmMessageReceived = channel.unary_unary(
                '/flwr.proto.Runtime/ConfirmMessageReceived',
                request_serializer=flwr_dot_proto_dot_message__pb2.ConfirmMessageReceivedRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_message__pb2.ConfirmMessageReceivedResponse.FromString,
                _registered_method=True)
        self.CreateTask = channel.unary_unary(
                '/flwr.proto.Runtime/CreateTask',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.StartAutomation = channel.unary_unary(
                '/flwr.proto.Runtime/StartAutomation',
                request_serializer=flwr_dot_proto_dot_control__pb2.StartAutomationRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_control__pb2.StartAutomationResponse.FromString,
                _registered_method=True)
        self.PushTaskMessage = channel.unary_unary(
                '/flwr.proto.Runtime/PushTaskMessage',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PushTaskMessageRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PushTaskMessageResponse.FromString,
                _registered_method=True)
        self.PushTaskEvents = channel.unary_unary(
                '/flwr.proto.Runtime/PushTaskEvents',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PushTaskEventsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PushTaskEventsResponse.FromString,
                _registered_method=True)
        self.PullTaskMessage = channel.unary_unary(
                '/flwr.proto.Runtime/PullTaskMessage',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PullTaskMessageRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PullTaskMessageResponse.FromString,
                _registered_method=True)
        self.RecordTaskUsage = channel.unary_unary(
                '/flwr.proto.Runtime/RecordTaskUsage',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.RecordTaskUsageRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.RecordTaskUsageResponse.FromString,
                _registered_method=True)
        self.GetConnector = channel.unary_unary(
                '/flwr.proto.Runtime/GetConnector',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.GetConnectorRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.GetConnectorResponse.FromString,
                _registered_method=True)
        self.PushLogs = channel.unary_unary(
                '/flwr.proto.Runtime/PushLogs',
                request_serializer=flwr_dot_proto_dot_log__pb2.PushLogsRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_log__pb2.PushLogsResponse.FromString,
                _registered_method=True)
        self.PushMessages = channel.unary_unary(
                '/flwr.proto.Runtime/PushMessages',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PushAppMessagesRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PushAppMessagesResponse.FromString,
                _registered_method=True)
        self.PullMessages = channel.unary_unary(
                '/flwr.proto.Runtime/PullMessages',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.PullAppMessagesRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.PullAppMessagesResponse.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/flwr.proto.Runtime/GetNodes',
                request_serializer=flwr_dot_proto_dot_runtime__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=flwr_dot_proto_dot_runtime__pb2.GetNodesResponse.FromString,
                _registered_method=True)


class RuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PullPendingTasks(self, request, context):
        """///////////////////////////////////////////////////////////////////////////
        General Runtime endpoints for SuperExec processes
        ///////////////////////////////////////////////////////////////////////////

        Pull pending tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTask(self, request, context):
        """Claim task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """///////////////////////////////////////////////////////////////////////////
        General Runtime endpoints for App Executor processes
        ///////////////////////////////////////////////////////////////////////////

        Get run details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTaskHeartbeat(self, request, context):
        """Task heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullTaskInput(self, request, context):
        """Pull task inputs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushTaskOutput(self, request, context):
        """Push task outputs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushObject(self, request, context):
        """///////////////////////////////////////////////////////////////////////////
        Object and task endpoints
        ///////////////////////////////////////////////////////////////////////////

        Push Object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullObject(self, request, context):
        """Pull Object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmMessageReceived(self, request, context):
        """Confirm Message Received
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTask(self, request, context):
        """Create a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAutomation(self, request, context):
        """Start an automation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushTaskMessage(self, request, context):
        """Push task message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushTaskEvents(self, request, context):
        """Push task events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullTaskMessage(self, request, context):
        """Pull task messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTaskUsage(self, request, context):
        """Record task usage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnector(self, request, context):
        """Resolve credentials for the authenticated connector task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushLogs(self, request, context):
        """Push task logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushMessages(self, request, context):
        """///////////////////////////////////////////////////////////////////////////
        Message and node endpoints
        ///////////////////////////////////////////////////////////////////////////

        Push messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullMessages(self, request, context):
        """Pull messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Return a set of nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullPendingTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.PullPendingTasks,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PullPendingTasksRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PullPendingTasksResponse.SerializeToString,
            ),
            'ClaimTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTask,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.ClaimTaskRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.ClaimTaskResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=flwr_dot_proto_dot_run__pb2.GetRunRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_run__pb2.GetRunResponse.SerializeToString,
            ),
            'SendTaskHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTaskHeartbeat,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.SendTaskHeartbeatRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.SendTaskHeartbeatResponse.SerializeToString,
            ),
            'PullTaskInput': grpc.unary_unary_rpc_method_handler(
                    servicer.PullTaskInput,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PullTaskInputRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PullTaskInputResponse.SerializeToString,
            ),
            'PushTaskOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.PushTaskOutput,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PushTaskOutputRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PushTaskOutputResponse.SerializeToString,
            ),
            'PushObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PushObject,
                    request_deserializer=flwr_dot_proto_dot_message__pb2.PushObjectRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_message__pb2.PushObjectResponse.SerializeToString,
            ),
            'PullObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PullObject,
                    request_deserializer=flwr_dot_proto_dot_message__pb2.PullObjectRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_message__pb2.PullObjectResponse.SerializeToString,
            ),
            'ConfirmMessageReceived': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmMessageReceived,
                    request_deserializer=flwr_dot_proto_dot_message__pb2.ConfirmMessageReceivedRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_message__pb2.ConfirmMessageReceivedResponse.SerializeToString,
            ),
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.CreateTaskRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.CreateTaskResponse.SerializeToString,
            ),
            'StartAutomation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAutomation,
                    request_deserializer=flwr_dot_proto_dot_control__pb2.StartAutomationRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_control__pb2.StartAutomationResponse.SerializeToString,
            ),
            'PushTaskMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PushTaskMessage,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PushTaskMessageRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PushTaskMessageResponse.SerializeToString,
            ),
            'PushTaskEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.PushTaskEvents,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PushTaskEventsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PushTaskEventsResponse.SerializeToString,
            ),
            'PullTaskMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PullTaskMessage,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PullTaskMessageRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PullTaskMessageResponse.SerializeToString,
            ),
            'RecordTaskUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTaskUsage,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.RecordTaskUsageRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.RecordTaskUsageResponse.SerializeToString,
            ),
            'GetConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnector,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.GetConnectorRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.GetConnectorResponse.SerializeToString,
            ),
            'PushLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.PushLogs,
                    request_deserializer=flwr_dot_proto_dot_log__pb2.PushLogsRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_log__pb2.PushLogsResponse.SerializeToString,
            ),
            'PushMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMessages,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PushAppMessagesRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PushAppMessagesResponse.SerializeToString,
            ),
            'PullMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.PullMessages,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.PullAppMessagesRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.PullAppMessagesResponse.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=flwr_dot_proto_dot_runtime__pb2.GetNodesRequest.FromString,
                    response_serializer=flwr_dot_proto_dot_runtime__pb2.GetNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flwr.proto.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flwr.proto.Runtime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runtime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PullPendingTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PullPendingTasks',
            flwr_dot_proto_dot_runtime__pb2.PullPendingTasksRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PullPendingTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/ClaimTask',
            flwr_dot_proto_dot_runtime__pb2.ClaimTaskRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.ClaimTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/GetRun',
            flwr_dot_proto_dot_run__pb2.GetRunRequest.SerializeToString,
            flwr_dot_proto_dot_run__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTaskHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/SendTaskHeartbeat',
            flwr_dot_proto_dot_runtime__pb2.SendTaskHeartbeatRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.SendTaskHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullTaskInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PullTaskInput',
            flwr_dot_proto_dot_runtime__pb2.PullTaskInputRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PullTaskInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushTaskOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PushTaskOutput',
            flwr_dot_proto_dot_runtime__pb2.PushTaskOutputRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PushTaskOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PushObject',
            flwr_dot_proto_dot_message__pb2.PushObjectRequest.SerializeToString,
            flwr_dot_proto_dot_message__pb2.PushObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PullObject',
            flwr_dot_proto_dot_message__pb2.PullObjectRequest.SerializeToString,
            flwr_dot_proto_dot_message__pb2.PullObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmMessageReceived(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/ConfirmMessageReceived',
            flwr_dot_proto_dot_message__pb2.ConfirmMessageReceivedRequest.SerializeToString,
            flwr_dot_proto_dot_message__pb2.ConfirmMessageReceivedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/CreateTask',
            flwr_dot_proto_dot_runtime__pb2.CreateTaskRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAutomation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/StartAutomation',
            flwr_dot_proto_dot_control__pb2.StartAutomationRequest.SerializeToString,
            flwr_dot_proto_dot_control__pb2.StartAutomationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushTaskMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PushTaskMessage',
            flwr_dot_proto_dot_runtime__pb2.PushTaskMessageRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PushTaskMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PushTaskEvents',
            flwr_dot_proto_dot_runtime__pb2.PushTaskEventsRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PushTaskEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullTaskMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PullTaskMessage',
            flwr_dot_proto_dot_runtime__pb2.PullTaskMessageRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PullTaskMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTaskUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/RecordTaskUsage',
            flwr_dot_proto_dot_runtime__pb2.RecordTaskUsageRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.RecordTaskUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/GetConnector',
            flwr_dot_proto_dot_runtime__pb2.GetConnectorRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.GetConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PushLogs',
            flwr_dot_proto_dot_log__pb2.PushLogsRequest.SerializeToString,
            flwr_dot_proto_dot_log__pb2.PushLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PushMessages',
            flwr_dot_proto_dot_runtime__pb2.PushAppMessagesRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PushAppMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/PullMessages',
            flwr_dot_proto_dot_runtime__pb2.PullAppMessagesRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.PullAppMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flwr.proto.Runtime/GetNodes',
            flwr_dot_proto_dot_runtime__pb2.GetNodesRequest.SerializeToString,
            flwr_dot_proto_dot_runtime__pb2.GetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
