"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import collections.abc
import flwr.proto.fab_pb2
import flwr.proto.federation_config_pb2
import flwr.proto.message_pb2
import flwr.proto.node_pb2
import flwr.proto.run_pb2
import flwr.proto.task_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PullPendingTasksRequest(google.protobuf.message.Message):
    """PullPendingTasks messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PullPendingTasksRequest = PullPendingTasksRequest

@typing.final
class PullPendingTasksResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASKS_FIELD_NUMBER: builtins.int
    @property
    def tasks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.task_pb2.Task]: ...
    def __init__(
        self,
        *,
        tasks: collections.abc.Iterable[flwr.proto.task_pb2.Task] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tasks", b"tasks"]) -> None: ...

global___PullPendingTasksResponse = PullPendingTasksResponse

@typing.final
class ClaimTaskRequest(google.protobuf.message.Message):
    """ClaimTask messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    task_id: builtins.int
    def __init__(
        self,
        *,
        task_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["task_id", b"task_id"]) -> None: ...

global___ClaimTaskRequest = ClaimTaskRequest

@typing.final
class ClaimTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_token", b"_token", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_token", b"_token", "token", b"token"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_token", b"_token"]) -> typing.Literal["token"] | None: ...

global___ClaimTaskResponse = ClaimTaskResponse

@typing.final
class SendTaskHeartbeatRequest(google.protobuf.message.Message):
    """SendTaskHeartbeat messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SendTaskHeartbeatRequest = SendTaskHeartbeatRequest

@typing.final
class SendTaskHeartbeatResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

global___SendTaskHeartbeatResponse = SendTaskHeartbeatResponse

@typing.final
class PushAppMessagesRequest(google.protobuf.message.Message):
    """PushAppMessages messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_LIST_FIELD_NUMBER: builtins.int
    MESSAGE_OBJECT_TREES_FIELD_NUMBER: builtins.int
    @property
    def messages_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.message_pb2.Message]: ...
    @property
    def message_object_trees(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.message_pb2.ObjectTree]: ...
    def __init__(
        self,
        *,
        messages_list: collections.abc.Iterable[flwr.proto.message_pb2.Message] | None = ...,
        message_object_trees: collections.abc.Iterable[flwr.proto.message_pb2.ObjectTree] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_object_trees", b"message_object_trees", "messages_list", b"messages_list"]) -> None: ...

global___PushAppMessagesRequest = PushAppMessagesRequest

@typing.final
class PushAppMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_IDS_FIELD_NUMBER: builtins.int
    OBJECTS_TO_PUSH_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    @property
    def message_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def objects_to_push(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        message_ids: collections.abc.Iterable[builtins.str] | None = ...,
        objects_to_push: collections.abc.Iterable[builtins.str] | None = ...,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_ids", b"message_ids", "objects_to_push", b"objects_to_push", "session_id", b"session_id"]) -> None: ...

global___PushAppMessagesResponse = PushAppMessagesResponse

@typing.final
class PullAppMessagesRequest(google.protobuf.message.Message):
    """PullAppMessages messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_IDS_FIELD_NUMBER: builtins.int
    @property
    def message_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        message_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_ids", b"message_ids"]) -> None: ...

global___PullAppMessagesRequest = PullAppMessagesRequest

@typing.final
class PullAppMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_LIST_FIELD_NUMBER: builtins.int
    MESSAGE_OBJECT_TREES_FIELD_NUMBER: builtins.int
    @property
    def messages_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.message_pb2.Message]: ...
    @property
    def message_object_trees(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.message_pb2.ObjectTree]: ...
    def __init__(
        self,
        *,
        messages_list: collections.abc.Iterable[flwr.proto.message_pb2.Message] | None = ...,
        message_object_trees: collections.abc.Iterable[flwr.proto.message_pb2.ObjectTree] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_object_trees", b"message_object_trees", "messages_list", b"messages_list"]) -> None: ...

global___PullAppMessagesResponse = PullAppMessagesResponse

@typing.final
class GetNodesRequest(google.protobuf.message.Message):
    """GetNodes messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetNodesRequest = GetNodesRequest

@typing.final
class GetNodesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.node_pb2.Node]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Iterable[flwr.proto.node_pb2.Node] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nodes", b"nodes"]) -> None: ...

global___GetNodesResponse = GetNodesResponse

@typing.final
class PushTaskMessageRequest(google.protobuf.message.Message):
    """PushTaskMessage messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> flwr.proto.message_pb2.Message: ...
    def __init__(
        self,
        *,
        message: flwr.proto.message_pb2.Message | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___PushTaskMessageRequest = PushTaskMessageRequest

@typing.final
class PushTaskMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_id", b"message_id"]) -> None: ...

global___PushTaskMessageResponse = PushTaskMessageResponse

@typing.final
class PushTaskEventsRequest(google.protobuf.message.Message):
    """PushTaskEvents messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.task_pb2.TaskEvent]: ...
    def __init__(
        self,
        *,
        events: collections.abc.Iterable[flwr.proto.task_pb2.TaskEvent] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["events", b"events"]) -> None: ...

global___PushTaskEventsRequest = PushTaskEventsRequest

@typing.final
class PushTaskEventsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PushTaskEventsResponse = PushTaskEventsResponse

@typing.final
class PullTaskMessageRequest(google.protobuf.message.Message):
    """PullTaskMessage messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIMIT_FIELD_NUMBER: builtins.int
    limit: builtins.int
    def __init__(
        self,
        *,
        limit: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_limit", b"_limit", "limit", b"limit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_limit", b"_limit", "limit", b"limit"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_limit", b"_limit"]) -> typing.Literal["limit"] | None: ...

global___PullTaskMessageRequest = PullTaskMessageRequest

@typing.final
class PullTaskMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[flwr.proto.message_pb2.Message]: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[flwr.proto.message_pb2.Message] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["messages", b"messages"]) -> None: ...

global___PullTaskMessageResponse = PullTaskMessageResponse

@typing.final
class RecordTaskUsageRequest(google.protobuf.message.Message):
    """RecordTaskUsage messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_USAGE_FIELD_NUMBER: builtins.int
    @property
    def task_usage(self) -> flwr.proto.task_pb2.TaskUsage: ...
    def __init__(
        self,
        *,
        task_usage: flwr.proto.task_pb2.TaskUsage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["task_usage", b"task_usage"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["task_usage", b"task_usage"]) -> None: ...

global___RecordTaskUsageRequest = RecordTaskUsageRequest

@typing.final
class RecordTaskUsageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RecordTaskUsageResponse = RecordTaskUsageResponse

@typing.final
class GetConnectorRequest(google.protobuf.message.Message):
    """GetConnector messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetConnectorRequest = GetConnectorRequest

@typing.final
class GetConnectorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    CREDENTIALS_JSON_FIELD_NUMBER: builtins.int
    CONFIG_JSON_FIELD_NUMBER: builtins.int
    connector_ref: builtins.str
    credentials_json: builtins.str
    config_json: builtins.str
    def __init__(
        self,
        *,
        connector_ref: builtins.str = ...,
        credentials_json: builtins.str = ...,
        config_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["config_json", b"config_json", "connector_ref", b"connector_ref", "credentials_json", b"credentials_json"]) -> None: ...

global___GetConnectorResponse = GetConnectorResponse

@typing.final
class PullTaskInputRequest(google.protobuf.message.Message):
    """PullTaskInput messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PullTaskInputRequest = PullTaskInputRequest

@typing.final
class PullTaskInputResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    RUN_FIELD_NUMBER: builtins.int
    FAB_FIELD_NUMBER: builtins.int
    FEDERATION_CONFIG_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    task_id: builtins.int
    @property
    def context(self) -> flwr.proto.message_pb2.Context: ...
    @property
    def run(self) -> flwr.proto.run_pb2.Run: ...
    @property
    def fab(self) -> flwr.proto.fab_pb2.Fab: ...
    @property
    def federation_config(self) -> flwr.proto.federation_config_pb2.SimulationConfig: ...
    def __init__(
        self,
        *,
        context: flwr.proto.message_pb2.Context | None = ...,
        run: flwr.proto.run_pb2.Run | None = ...,
        fab: flwr.proto.fab_pb2.Fab | None = ...,
        federation_config: flwr.proto.federation_config_pb2.SimulationConfig | None = ...,
        task_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context", "fab", b"fab", "federation_config", b"federation_config", "run", b"run"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "fab", b"fab", "federation_config", b"federation_config", "run", b"run", "task_id", b"task_id"]) -> None: ...

global___PullTaskInputResponse = PullTaskInputResponse

@typing.final
class PushTaskOutputRequest(google.protobuf.message.Message):
    """PushTaskOutput messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    SUB_STATUS_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    CLIENTAPP_RUNTIME_FIELD_NUMBER: builtins.int
    sub_status: builtins.str
    details: builtins.str
    clientapp_runtime: builtins.float
    """Simulation Runtime usage only."""
    @property
    def context(self) -> flwr.proto.message_pb2.Context: ...
    def __init__(
        self,
        *,
        context: flwr.proto.message_pb2.Context | None = ...,
        sub_status: builtins.str = ...,
        details: builtins.str = ...,
        clientapp_runtime: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_clientapp_runtime", b"_clientapp_runtime", "clientapp_runtime", b"clientapp_runtime", "context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_clientapp_runtime", b"_clientapp_runtime", "clientapp_runtime", b"clientapp_runtime", "context", b"context", "details", b"details", "sub_status", b"sub_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_clientapp_runtime", b"_clientapp_runtime"]) -> typing.Literal["clientapp_runtime"] | None: ...

global___PushTaskOutputRequest = PushTaskOutputRequest

@typing.final
class PushTaskOutputResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PushTaskOutputResponse = PushTaskOutputResponse

@typing.final
class CreateTaskRequest(google.protobuf.message.Message):
    """CreateTask messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    FAB_HASH_FIELD_NUMBER: builtins.int
    MODEL_REF_FIELD_NUMBER: builtins.int
    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    type: builtins.str
    fab_hash: builtins.str
    model_ref: builtins.str
    connector_ref: builtins.str
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        fab_hash: builtins.str | None = ...,
        model_ref: builtins.str | None = ...,
        connector_ref: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_connector_ref", b"_connector_ref", "_fab_hash", b"_fab_hash", "_model_ref", b"_model_ref", "connector_ref", b"connector_ref", "fab_hash", b"fab_hash", "model_ref", b"model_ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_connector_ref", b"_connector_ref", "_fab_hash", b"_fab_hash", "_model_ref", b"_model_ref", "connector_ref", b"connector_ref", "fab_hash", b"fab_hash", "model_ref", b"model_ref", "type", b"type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_connector_ref", b"_connector_ref"]) -> typing.Literal["connector_ref"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fab_hash", b"_fab_hash"]) -> typing.Literal["fab_hash"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_model_ref", b"_model_ref"]) -> typing.Literal["model_ref"] | None: ...

global___CreateTaskRequest = CreateTaskRequest

@typing.final
class CreateTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    task_id: builtins.int
    def __init__(
        self,
        *,
        task_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_task_id", b"_task_id", "task_id", b"task_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_task_id", b"_task_id", "task_id", b"task_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_task_id", b"_task_id"]) -> typing.Literal["task_id"] | None: ...

global___CreateTaskResponse = CreateTaskResponse
