"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Task(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PENDING_AT_FIELD_NUMBER: builtins.int
    STARTING_AT_FIELD_NUMBER: builtins.int
    RUNNING_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    FAB_HASH_FIELD_NUMBER: builtins.int
    MODEL_REF_FIELD_NUMBER: builtins.int
    CONNECTOR_REF_FIELD_NUMBER: builtins.int
    task_id: builtins.int
    type: builtins.str
    run_id: builtins.int
    pending_at: builtins.str
    starting_at: builtins.str
    running_at: builtins.str
    finished_at: builtins.str
    fab_hash: builtins.str
    model_ref: builtins.str
    connector_ref: builtins.str
    @property
    def status(self) -> global___TaskStatus: ...
    def __init__(
        self,
        *,
        task_id: builtins.int = ...,
        type: builtins.str = ...,
        run_id: builtins.int = ...,
        status: global___TaskStatus | None = ...,
        pending_at: builtins.str = ...,
        starting_at: builtins.str = ...,
        running_at: builtins.str = ...,
        finished_at: builtins.str = ...,
        fab_hash: builtins.str | None = ...,
        model_ref: builtins.str | None = ...,
        connector_ref: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_connector_ref", b"_connector_ref", "_fab_hash", b"_fab_hash", "_model_ref", b"_model_ref", "connector_ref", b"connector_ref", "fab_hash", b"fab_hash", "model_ref", b"model_ref", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_connector_ref", b"_connector_ref", "_fab_hash", b"_fab_hash", "_model_ref", b"_model_ref", "connector_ref", b"connector_ref", "fab_hash", b"fab_hash", "finished_at", b"finished_at", "model_ref", b"model_ref", "pending_at", b"pending_at", "run_id", b"run_id", "running_at", b"running_at", "starting_at", b"starting_at", "status", b"status", "task_id", b"task_id", "type", b"type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_connector_ref", b"_connector_ref"]) -> typing.Literal["connector_ref"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fab_hash", b"_fab_hash"]) -> typing.Literal["fab_hash"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_model_ref", b"_model_ref"]) -> typing.Literal["model_ref"] | None: ...

global___Task = Task

@typing.final
class TaskStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    SUB_STATUS_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    status: builtins.str
    """"pending", "starting", "running", or "finished" """
    sub_status: builtins.str
    """"completed", "failed", "stopped" or "" (non-finished)"""
    details: builtins.str
    """failure details"""
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        sub_status: builtins.str = ...,
        details: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["details", b"details", "status", b"status", "sub_status", b"sub_status"]) -> None: ...

global___TaskStatus = TaskStatus

@typing.final
class TaskEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    id: builtins.int
    timestamp: builtins.str
    run_id: builtins.int
    task_id: builtins.int
    event: builtins.str
    data: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        timestamp: builtins.str = ...,
        run_id: builtins.int = ...,
        task_id: builtins.int = ...,
        event: builtins.str = ...,
        data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "event", b"event", "id", b"id", "run_id", b"run_id", "task_id", b"task_id", "timestamp", b"timestamp"]) -> None: ...

global___TaskEvent = TaskEvent

@typing.final
class TaskUsage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USAGE_TYPE_FIELD_NUMBER: builtins.int
    INPUT_TOKENS_FIELD_NUMBER: builtins.int
    OUTPUT_TOKENS_FIELD_NUMBER: builtins.int
    TOTAL_TOKENS_FIELD_NUMBER: builtins.int
    PROVIDER_FIELD_NUMBER: builtins.int
    usage_type: builtins.str
    input_tokens: builtins.int
    output_tokens: builtins.int
    total_tokens: builtins.int
    provider: builtins.str
    def __init__(
        self,
        *,
        usage_type: builtins.str = ...,
        input_tokens: builtins.int | None = ...,
        output_tokens: builtins.int | None = ...,
        total_tokens: builtins.int | None = ...,
        provider: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_input_tokens", b"_input_tokens", "_output_tokens", b"_output_tokens", "_total_tokens", b"_total_tokens", "input_tokens", b"input_tokens", "output_tokens", b"output_tokens", "total_tokens", b"total_tokens"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_input_tokens", b"_input_tokens", "_output_tokens", b"_output_tokens", "_total_tokens", b"_total_tokens", "input_tokens", b"input_tokens", "output_tokens", b"output_tokens", "provider", b"provider", "total_tokens", b"total_tokens", "usage_type", b"usage_type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_input_tokens", b"_input_tokens"]) -> typing.Literal["input_tokens"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_output_tokens", b"_output_tokens"]) -> typing.Literal["output_tokens"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_total_tokens", b"_total_tokens"]) -> typing.Literal["total_tokens"] | None: ...

global___TaskUsage = TaskUsage
