[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-jax"
version = "1.1.9"
description = "Federated Learning with JAX and Flower (Quickstart Example)"
license = {file = "LICENSE"}
dependencies = [
    "flwr[simulation]>=1.28.0",
    "flwr-datasets[vision]>=0.6.0",
    "jax==0.4.36",
    "jaxlib==0.4.36",
    "flax==0.10.2",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"
fab-format-version = 1
flwr-version-target = "1.33.0"

[tool.flwr.app.components]
serverapp = "jaxexample.server_app:app"
clientapp = "jaxexample.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 5
learning-rate = 0.1
fraction-evaluate = 1.0
batch-size = 64
save-model = false
